### ISSUE TITLE
Xfce Desktop File Name Bug

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [actionless/oomox#107]
![screenshot_2017-11-19_13-48-18](https://user-images.githubusercontent.com/7698035/32991290-5339be0a-cd30-11e7-818d-146bb2876b19.png)
So I made a dark variant of Numix based on the Ambience colour scheme (from default Ubuntu) through oomox, thanks to this I was able to create something pretty great (so thank you.

However, to make the text readable when highlighted I need to make the selection text black. As a result of doing this the text of files on the desktop in XFCE becomes black too and is unreadable.

**Comment by actionless** [comment]
is your fxce using gtk2 or gtk3?

**Comment by KUPOinyourWINDOW** [comment]
GTK2 I believe. As I understand it whilst it does support GTK3, and the themes I use are GTK3, not all of the system applications (probably including the desktop) are using it, so I think it defaults to GTK2.

If it helps, I'm using the newest version of Xubuntu.

**Comment by actionless** [comment]
btw are you able to reproduce the border issue in xfce?
https://github.com/actionless/oomox-gtk-theme/issues/10

**Comment by KUPOinyourWINDOW** [comment]
Yes, I've left a comment over there with a screenshot for you

**Comment by actionless** [comment]
thanks! i'm going to install a vm with xfce soon to have a look since there are few different issues with it
