### ISSUE TITLE
Minor XFCE Arrow Visual Bug

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [actionless/oomox#108]
![screenshot_2017-11-19_16-10-38](https://user-images.githubusercontent.com/7698035/32992579-44b028ec-cd44-11e7-975a-4f10394f940c.png)

When you open up a music player, then go into the XFCE sound menu (which is GTK3) the arrows that appear to scroll have an ugly white highlight colour. Thanks for your time and work!

**Comment by actionless** [comment]
does it have it only on hover or always?

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#11
