### ISSUE TITLE
Cannot export theme without the compact option enabled.

### ISSUE THREAD

**Issue by nivekxyz** [actionless/oomox#109]
Maybe I am doing something wrong but when I clone the repo I am not getting all the files. I have even tried the download button on the page. For whatever reason the materia-theme folder is empty. I have cloned the materia theme seperately and added the files to the appropriate place and everything seems to work ok but after it is finished generating the files I get an error on moving that says cannot stat /home/myusername/.themes/oomox-themename no such file or directory. I have tried to manually create the directory for it and still same error. I have been using this tool for months with no issues until now.

**Comment by actionless** [comment]
if you're installing it manually, please proceed to the manual install guide:
https://github.com/actionless/oomox#installation

could you copy the full error-text/make screenshot if still won't work?

**Comment by nivekxyz** [comment]
After some messing around, it turns out that I can export themes with the compact style option enabled without issue, I just cannot export themes without it. Very strange.

**Comment by actionless** [comment]
@nivekxyz i fixed that, you can wait before it will be merged and then reinstall `oomox-git` again (so it will fetch the latest git versions of both oomox and materia)

**Comment by actionless** [comment]
or you can install the unmerged version manually, by replacing in PKGBUILD the URL https://github.com/actionless/oomox/blob/master/PKGBUILD#L17:

From: "git+https://github.com/nana-4/materia-theme.git#branch=master"
To: "git+https://github.com/nana-4/Flat-Plat.git#branch=fix-changecolor-theme-rename"

**Comment by nivekxyz** [comment]
@actionless Thank you. Love this program, keep up the good work!
