### ISSUE TITLE
Dark themes w/ eclipse 

### ISSUE THREAD

**Issue by neeasade** [actionless/oomox#11]
They look bad - unsure if there's something related to gtk/oomox/numix/eclipse, but if using oomox and I use:

gnome_noble.sh: https://u.teknik.io/NJBzm1.png

gnome_noble_dark.sh: https://u.teknik.io/ZX9tJI.png

this is with eclipse mars on arch linux.

**Comment by actionless** [comment]
how it works with other dark themes? i don't have eclipse under the hand to check it

**Comment by neeasade** [comment]
ah snap maybe it is just eclipse.

with the delorean dark theme: https://u.teknik.io/K9fD9O.png

theme: http://killhellokitty.deviantart.com/art/Delorean-dark-3-12-5-08242014-476093824

**Comment by actionless** [comment]
looks like an eclipse thing, i think in firefox you could have the same issue with the tabs on the default firefox theme

**Comment by neeasade** [comment]
found the solution in the wiki: https://wiki.archlinux.org/index.php/Eclipse

under heading "Eclipse 4 not respecting dark/custom gtk themes resulting in white background"
