### ISSUE TITLE
Can't costumize Gnome top bar

### ISSUE THREAD

**Issue by tkosamja** [actionless/oomox#111]
Using the Materia theme, if I choose "Similar to background", the top bar just gets white/transparent with every color. If I choose "Contrast to background", I can choose the color when a windows is fullscreen but without that it goes white/transparent again.
This is really irritating since it doesn't fit my themes.

**Comment by actionless** [comment]
that option was removed from the latest oomox version because it was not working correctly and other options were added instead

please update and try again

**Comment by tkosamja** [comment]
I did and every time I try to export a theme I get the following error: 

```
unknown option --hidpi
usage: /opt/oomox/oomox_gui/../materia-theme/change_color.sh [-o OUTPUT_THEME_NAME] [-p PATH_LIST] PATH_TO_PRESET
examples:
       /opt/oomox/oomox_gui/../materia-theme/change_color.sh -o my-theme-name <(echo -e BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n)
       /opt/oomox/oomox_gui/../materia-theme/change_color.sh ../colors/retro/twg
```

**Comment by actionless** [comment]
have you installed app manually?

in that case you need to update it with the following command:
```sh
 git pull origin master --recurse-submodules
```

**Comment by tkosamja** [comment]
Nevermind, I fixed that but other problem emerged.
See this? https://s14.postimg.org/84at8r3v5/Screenshot_from_2017-12-29_11-16-06.png
I want the top bar black and the rest as is, but if I change from green to black all is going to be black. Can't I choose a custom color for the text?

**Comment by actionless** [comment]
try applying this patch to materia:

```patch
diff --git a/change_color.sh b/change_color.sh
index 5845cde..7909a47 100755
--- a/change_color.sh
+++ b/change_color.sh
@@ -128,6 +128,10 @@ cd ${tempdir}


 echo "== Converting theme into template..."
+sed -i'' \
+       -e 's/$black/%MENU_BG%/g' \
+       -e 's/$white/%MENU_FG%/g' \
+       ./src/gnome-shell/3.18/sass/_colors.scss
 for FILEPATH in "${PATHLIST[@]}"; do
        find "${FILEPATH}" -type f -exec sed -i'' \
                -e 's/^\(\$dark_fg_color:\).*;.*$/\1 %FG%;/g' \
```

**Comment by tkosamja** [comment]
Sorry if I should know this, but how am I supposed to apply the patch?

**Comment by actionless** [comment]
go to directory with materia theme, put the lines to some file, do `git apply your_file`

or just do that change manually :-)

**Comment by tkosamja** [comment]
It gives me an error:

```
error: patch failed: change_color.sh:128
error: change_color.sh: patch does not apply
```

**Comment by actionless** [comment]
could you show `git status` inside materia dir?

**Comment by tkosamja** [comment]
git apply patch.sh
```
error: patch failed: change_color.sh:128
error: change_color.sh: patch does not apply
```

git status
```
HEAD detached at a319344
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        patch.sh

nothing added to commit but untracked files present (use "git add" to track)
```

git add patch.sh
git status
```
HEAD detached at a319344
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   patch.sh
```

**Comment by actionless** [comment]
something wrong could happen with tabs/spaces when copy-pasting, so i've uploaded it as a file:
https://transfer.sh/QbYPJ/patch.diff

**Comment by tkosamja** [comment]
I don't think it changes anything. What was it supposed to do?

**Comment by actionless** [comment]
it had to make gnome panel use the same colors as menubar/toolbar/CSD

**Comment by tkosamja** [comment]
No, it does not change anything. Tried with different themes and different colours.

**Comment by actionless** [comment]
send one example theme on which you're trying i'll check it in a virtual machine

**Comment by tkosamja** [comment]
Sure, where are the exported themes located?

**Comment by actionless** [comment]
not exported theme but a theme file itself, user themes are located under `~/.config/oomox/colors/`

**Comment by tkosamja** [comment]
Ok here's one of the dark themes I made: https://transfer.sh/EHhpl/Apathy-Dark

**Comment by actionless** [comment]
i see the problem now:
`MATERIA_MENUBAR_STYLE=same` was removed from app but still in the theme, i'll fixed app to ignore it

**Comment by tkosamja** [comment]
Ok nice. Should I wait for the next update?

**Comment by actionless** [comment]
on which distro are you using it?

**Comment by tkosamja** [comment]
Antergos

**Comment by actionless** [comment]
![2018-01-01-150653_1120x984_scrot](https://user-images.githubusercontent.com/1655669/34468278-fca3a950-ef05-11e7-85af-b5440c4581d3.png)

**Comment by actionless** [comment]
just install `oomox-git` from AUR, it should already have the change:

**Comment by tkosamja** [comment]
After updating it, MATERIA_MENUBAR_STYLE=same was still there. 
I removed it from the theme and I must say that it improved but still it's not what I want.
As you can see here it's still transparent.
![screenshot from 2018-01-01 14-26-07](https://user-images.githubusercontent.com/26143003/34468394-d9de40fc-eeff-11e7-8ec7-857dd75696c7.png)
![screenshot from 2018-01-01 14-26-01](https://user-images.githubusercontent.com/26143003/34468395-da02ad66-eeff-11e7-9428-b2d5a597cd64.png)

**Comment by actionless** [comment]
right, it's an expected behavior for it to be semi-transparent

feel free to open another issue to request a new option to adjust transparency level
