### ISSUE TITLE
Applying Spotify themes. error hex_to_rgba.sh: line 23

### ISSUE THREAD

**Issue by ivarsu** [actionless/oomox#113]
/opt/oomox/oomoxify/scripts/hex_to_rgba.sh: line 23: printf: 0.55: invalid number
Installed using the latest .deb release on Ubuntu 17.10

**Comment by actionless** [comment]
could you run?

```bash
printf 'rgba(%i, %i, %i, %0.2f)\n' 10 100 200 0.55
locale
```

**Comment by ivarsu** [comment]
`printf 'rgba(%i, %i, %i, %0.2f)\n' 10 100 200 0.55` outputs `rgba(10, 100, 200, 0,55)`
`locale` outputs `LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=nb_NO.UTF-8
LC_TIME=nb_NO.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nb_NO.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nb_NO.UTF-8
LC_NAME=nb_NO.UTF-8
LC_ADDRESS=nb_NO.UTF-8
LC_TELEPHONE=nb_NO.UTF-8
LC_MEASUREMENT=nb_NO.UTF-8
LC_IDENTIFICATION=nb_NO.UTF-8
LC_ALL=
`

**Comment by actionless** [comment]
and `env LC_NUMERIC="C" printf 'rgba(%i, %i, %i, %0.2f)\n' 10 100 200 0.55`?

**Comment by ivarsu** [comment]
`zsh: no matches found: 0.55?`

**Comment by actionless** [comment]
you copypasted the question mark

**Comment by ivarsu** [comment]
right. yeah that worked, same result as previous.

**Comment by actionless** [comment]
how exactly?

**Comment by ivarsu** [comment]
`rgba(10, 100, 200, 0.55)`

**Comment by ivarsu** [comment]
Does not resolve the problem in the script.

**Comment by actionless** [comment]
try this package:

[oomox.tar.gz](https://github.com/actionless/oomox/files/1595440/oomox.tar.gz)

**Comment by ivarsu** [comment]
cant install it, gdebi gives `Failed to open the software package
The package might be corrupted or you are not allowed to open the file. Check the permissions of the file.`

**Comment by actionless** [comment]
could you try with `sudo dpkg -i`?

**Comment by actionless** [comment]
and first untar it if not

**Comment by ivarsu** [comment]
`sudo dpkg -i oomox.deb` outputs 
`dpkg-deb: error: 'oomox.deb' is not a debian format archive
dpkg: error processing archive oomox.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 oomox.deb
`

**Comment by actionless** [comment]
have you really untared it or just renamed?

**Comment by actionless** [comment]
just in case i've uploaded to a different place: https://transfer.sh/OggYk/oomox.deb

**Comment by ivarsu** [comment]
I am untaring it, but the problem was that the initial .deb you provided was corrupt or not compiled correctly. The file size of the tar.gz was only 137 bytes and the .deb was 10 Kb. the last .deb you provided however did the trick. And spotify themeing is working great, Thanks.

**Comment by actionless** [comment]
good to know what it's working now, thanks for reporting and testing
