### ISSUE TITLE
GTK doesn't use colors of some of the archdroid icons

### ISSUE THREAD

**Issue by bklaase** [actionless/oomox#118]
After updating gtk this morning I saw all SVG icons were black. Simply getting latest oomox and regenerating resolved it ... mostly. Except now for some icons (like tars) I get ugly icons were black is used in stead of theme color. It happens for both gtk2 and ~3 apps. but NOT qt apps (different svg rendering maybe?)

Here is a screenshot of the issue (thunar with ridiculous zoom for clarity, gtk 2.0) :
![image](https://user-images.githubusercontent.com/8513117/34944863-7e0a8d0a-fa01-11e7-995a-a0283188aad3.png)

qt app (pcmanfm-qt):
![image](https://user-images.githubusercontent.com/8513117/34944994-f561c738-fa01-11e7-84d7-a27f017f7ca1.png)

As you can see, it's much better here.

Any ideas?

**Comment by actionless** [comment]
because gtk is using librsvg and it have a bug between versions `2.41.2` and `2.42.1`

there is already a workaround applied to archdroid icons, so installing the latest version of oomox and generating icons again should solve the issue

**Comment by bklaase** [comment]
Thanks for pointing me in the direction of librsvg, I had tried reinstalling that, by now I now it's the issue. The workaround from 5 days ago gives me the picture of thunar you see in my OP. It resolved it only partially, but not for all the icons. 

It's fine, it's not a oomox issue anyway, and I can sit on a slightly older version of librsvg for a few weeks until they fix it. Thanks for replying so quickly!

**Comment by actionless** [comment]
i think part of icons are still black because it was some mistake in a regex which i've applied for the "conversion" of the icons

after lirsvg patch will arrive to archlinux stable line i'll just revert the latest change so the icons will be fine

**Comment by bklaase** [comment]
I'm indeed using archlinux and for me the instability is a very acceptable price for having easy access to the latest by default :). Since the latest commit is older then this issue, I'm guessing you won't be correcting the mistake in that regex? Not that I mind, but then I keep librsvg on 2.40 a while longer. :P

**Comment by actionless** [comment]
right, i am not going to, because i hope what new librsvg version should come soon (from the observation of latest release dates)
