### ISSUE TITLE
oomoxify.sh: No such file or directory

### ISSUE THREAD

**Issue by boardfish** [actionless/oomox#119]
```
/usr/bin/oomoxify-cli: line 3: /opt/oomox/oomoxify/oomoxify.sh: No such file or directory
```

Getting the above error when running the `oomoxify-cli` command in the README.md, but `oomoxify-cli` was installed on my PATH thanks to `pacaur`, so that's the only difference. 

```
oomoxify-cli /opt/oomox/colors/gnome-colors/shiki-noble
```

Exporting to Spotify via `oomox-gui` works fine, but I need to be able to do this via command line as it's something small I'd like [`pywal`](https://github/dylanaraps/pywal) to support.

I installed this on Manjaro by way of `pacaur -S oomox-git` as outlined in the `pywal` wiki for GTK2/3 themes. I'd like to be able to say what version I'm running but `oomox-cli` doesn't have a `--version` or `-v` flag, and `oomox-gui` has no pointers either, but given that it's from this repository it's likely the latest at the time.

**Comment by actionless** [comment]
thanks for reporting!

**Comment by boardfish** [comment]
How can I update `oomox-git` as installed currently? I've tried using `pacaur -u oomox-git` to no avail.

**Comment by boardfish** [comment]
Contents of `/usr/bin/oomoxify-cli` are as follows:

```
#!/bin/sh
cd /opt/oomox/
exec ./oomoxify/oomoxify.sh "$@"
```

I've done a search of the repo on GitHub and I'm not sure where this script gets made, so the /opt/oomox directory here needs swapping out. I'll do it manually on my install, but so that `oomoxify` can be used easily by other scripts independent of install location, it makes sense to make this change.

**Comment by actionless** [comment]
@boardfish i've updated the scripts' wrappers as well now, just install `oomox-git` again to see the change

**Comment by boardfish** [comment]
Looks good to me. Thanks for the fix!
