### ISSUE TITLE
GUI testing thread

### ISSUE THREAD

**Issue by spidernetlabs** [actionless/oomox#12]
Since gtk3 got updated to version 3.20 all themes needs to be updated, including this one.

Currently the theme is "broken": missing tab borders, missing volume sliders, etc.

See for reference: http://i.imgur.com/sI3nFFn.png
The same happens with this theme.

**Comment by actionless** [comment]
merged wip branch into master, it's not finished yet, but better than nothing:
https://github.com/actionless/oomox/pull/13

**Comment by spidernetlabs** [comment]
Thanks. Yeah, better than nothing! Keep up the good work ;)

**Comment by actionless** [comment]
Thanks! Also in few days i am going to finish GUI part (`./gui.sh`, atm it can only export themes, but not create/edit them), i will appreciate any help with testing it.

**Comment by spidernetlabs** [comment]
Sure. I'll be on the lookout for any update.

**Comment by actionless** [comment]
@spidernetlabs i just finished with minimal GUI functionality.
please  test

**Comment by spidernetlabs** [comment]
Cloning, modifying, saving a preset works.
Exporting a preset works but in the terminal output I get

`rm: cannot remove '/home/spidernet/.themes/oomox-gnome_noble': No such file or directory` oomox-gnome_noble is the preset I tried to export.
Plus a bunch of GTK-warnings above about some theme parsing errors that you probably already know about.

On a sidenote, I lost a preset I created, I only have the exported theme, is it possible to recover or recreate the template from the exported theme? If not it'd be a nice feature to implement.

**Comment by actionless** [comment]
thanks!
so it's all working fine except of some warning messages, right?

older versions of oomox were saving `current_colors.txt` to the exported theme root, i can enable it back again if you think it could be usable

colors can be manually observed in the first lines of `gtk-3.0/dist/gtk.css` (lines 5-12) or `gtk-2.0/gtkrc` (lines 3-4)

**Comment by spidernetlabs** [comment]
Thanks I got the preset back.

One more thing. If I try to load either the xresources or xresources2 from the preset list I got this error: http://i.imgur.com/hzVrwht.png (from `Traceback:`)
my xresources: http://nopaste.linux-dev.org/?1060884

**Comment by actionless** [comment]
`xresources*` and `random` themes atm can't be opened in gui because they're using some bash magic instead of defining colors explicitly so they can't be edited in GUI

i think i can add some workaround to be possible to export those themes via GUI but without possibility to edit, and preview will make sense only for xresources because random theme generates on each script invoke

**Comment by spidernetlabs** [comment]
Gotcha, didn't know about that. But since it was there I gave it a test and reported.
So all is working fine.

It'd be a nice feature, since I usually build themes around the colors in .xresources. So being able to import those colors and maybe edit them would be neat. If it's not possible, it's not a big deal.

**Comment by actionless** [comment]
preview almost finished atm

i think editing such bash themes could be easier in the text editor, mb i can just add a multiline text edit widget instead of colorpicker for such themes

**Comment by spidernetlabs** [comment]
No, I didn't mean to edit the xresources inside your GUI. I meant importing the bash colors inside the GUI so I can export a theme based around the bash colors. I don't know if you know what I mean.

**Comment by actionless** [comment]
pushed to the master, please test

**Comment by spidernetlabs** [comment]
http://i.imgur.com/C4zlTJY.png

**Comment by actionless** [comment]
weird, with which theme did that happened? have you edited it?

**Comment by spidernetlabs** [comment]
I tried clicking on xresources.

**Comment by actionless** [comment]
could you add to `./gui/helpers.py`:

```
 89     i = 0
+    print(lines)
 90     for key in THEME_KEYS:
```

**Comment by spidernetlabs** [comment]
http://i.imgur.com/hHV9PLc.png seems to be empty?

**Comment by actionless** [comment]
please pull master and try again

**Comment by spidernetlabs** [comment]
Same: http://i.imgur.com/gpEMAiU.png

**Comment by actionless** [comment]
and does it works for `random` theme? if so, check if `xrdb` executable is in your path

**Comment by spidernetlabs** [comment]
Random works, xrdb is in the path, but `xrdb -query` output is empty. That could be the problem. That's strange, I have `[[ -f ~/.Xresources ]] && xrdb -merge ~.Xresources` in my .xinitrc

**Comment by spidernetlabs** [comment]
Fixed the xrdb issue. Now everything is working fine.

**Comment by actionless** [comment]
thanks for testing, please open a new bug/feature request if you'll notice anything more
