### ISSUE TITLE
Window border gap on Gnome

### ISSUE THREAD

**Issue by jwhipp** [actionless/oomox#121]
I'm on Ubuntu 17.01 with Gnome 3.26.

I've tried with the Materia and Numix options, when setting the theme created by Oomox, I end up with a Window border that has about a two pixel gap between the edge of the Window and the border.   I am not seeing any border thickness options in the create tool.  Doesn't seem to happen on all windows, Chrome and gnome specific apps seem unaffected. 

![selection_001](https://user-images.githubusercontent.com/556332/35291869-f0d3c59c-002b-11e8-9163-40e7596db9b7.png)

Attached screen shot is of the Slack Linux app.

**Comment by actionless** [comment]
if it displayed fine if gtk2 theme set to oomox but WM decorations theme is different?
and if the opposite?

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#23
