### ISSUE TITLE
Font size in Oomoxify on a High Resolution display

### ISSUE THREAD

**Issue by hazmish** [actionless/oomox#122]
I feel as this is a problem with my own stupidity and unfamiliarity with GTK. However, when I try exporting a theme with a custom font to Spotify it turns up super small (I have a 4k monitor which is seeming to be the problem). When the font is entered to the custom font field for export to spotify, is there some way to specify size?

Thanks.

**Comment by actionless** [comment]
just do normal `Ctrl`+`++
