### ISSUE TITLE
Better qt5 theme generation

### ISSUE THREAD

**Issue by angarod** [actionless/oomox#124]
I'm using oomox with pywal for generating my colorscheme and i noticed qt5 theme based on gtk2 is not pretty. Some apps like virtualbox and nextcloud client are mixing white and black colours.

**Comment by actionless** [comment]
you can propose your fix here:
https://github.com/actionless/oomox-gtk-theme/blob/master/src/qt5ct_palette.conf

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#22
