### ISSUE TITLE
Disable support for unnecessary environments

### ISSUE THREAD

**Issue by Mauladen** [actionless/oomox#125]
At the moment I'm using BSPWM and I don't need support: 

* GNOME Shell 
* Budgie 
* MATE 
* Unity 

Maybe we should think about the functionality which will allow you to disable it?

**Comment by actionless** [comment]
that wouldn't affect theme generation time anyway so turning that into some options will both encomplicate code and user interface for no reason

**Comment by actionless** [comment]
btw, for speed optimization currentl GTK+3 theme generated only for current gtk version, later on i am planning to add an option to generate all available (that option already exist in oomox-cli)

btw in cli you can also exclude unnecessary themes:
https://github.com/actionless/oomox-gtk-theme/blob/988581250249b3244cb80ac345ad73925a391d70/change_color.sh#L25-L26
https://github.com/actionless/oomox-gtk-theme/blob/988581250249b3244cb80ac345ad73925a391d70/change_color.sh#L72-L87
