### ISSUE TITLE
Could you tell me how to install oomox flatpak?

### ISSUE THREAD

**Issue by chemel9** [actionless/oomox#131]
hi, i like your application, and i would to install oomox flatpak
could you tell me how to install oomox flatpak?

Does oomox is available on flathub repository?

**Comment by actionless** [comment]
it have scripts with which i've managed to build it locally:
https://github.com/actionless/oomox#flatpak

however it seems what result is not really reliable:
https://github.com/actionless/oomox/issues/127
https://github.com/flathub/flathub/pull/265

i think it would make sense using it when it will reach at least version 1.0

so i would recommend either some other installation way listed in readme, or if you want oomox running inside the container to try using docker:
https://github.com/actionless/oomox-gtk-theme/blob/master/Dockerfile (this one is configured only for oomox gtk theme, but if you have interest i can update it to run full oomox set)

to run GUI apps inside docker you can use such wrapper script:
https://github.com/actionless/oomox-gtk-theme/blob/master/docker_scripts/debug_docker.sh

**Comment by actionless** [comment]
@chemel9 did you get it to work? :-)

**Comment by chemel9** [comment]
yes, i used the deb package, it works correctly
but the flatpak version doesn't work
