### ISSUE TITLE
oomox-cli failing to generate theme

### ISSUE THREAD

**Issue by wilberanderson** [actionless/oomox#132]
So the error originally came from my `wal` script after reinstalling wal and oomox, but I've narrowed it down to being an `oomox-cli` problem.

Here is an example of running it:

```
oomox-cli -o test /home/wilber/.cache/wal/colors-oomox
rm: cannot remove '/home/wilber/.themes/test': No such file or directory
rm -rf "gtk-3.0/dist"
rm -f "gtk-3.0/gtk.gesource"
rm -rf "gtk-3.20/dist"
rm -f "gtk-3.20/gtk.gresource"
rm -rf "/home/wilber/.themes/test/dist"
mkdir -p gtk-3.0/dist
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk.scss" "gtk-3.0/dist/gtk.css"
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk-dark.scss" "gtk-3.0/dist/gtk-dark.css"
glib-compile-resources --sourcedir="gtk-3.0" "gtk-3.0/gtk.gresource.xml"
mkdir -p gtk-3.20/dist
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
Error: 0.24706 isn't a valid CSS value.
        on line 340 of gtk-3.20/scss/widgets/_view.scss
>>   border: 1px solid alpha($borders_color, (lightness($bg_color))/100% + .2);
   ------------------------------------------^
Makefile:27: recipe for target 'css_gtk320' failed
make: *** [css_gtk320] Error 1

```

Here is the contents of `colors-oomox`:

```
NAME=wal
BG=060B12
FG=e3cea3
MENU_BG=060B12
MENU_FG=e3cea3
SEL_BG=595B6A
SEL_FG=060B12
TXT_BG=060B12
TXT_FG=e3cea3
BTN_BG=6E6975
BTN_FG=e3cea3
HDR_BTN_BG=B83749
HDR_BTN_FG=e3cea3
GTK3_GENERATE_DARK=True
ROUNDNESS=0
SPACING=3
GRADIENT=0.0
```

When I select the theme (that failed to generate), it has no colors and a completely transparent gtk background. Selecting the `-m gtk3` switch stops the error from happening, but it still gives a transparent gtk theme.

**Comment by actionless** [comment]
seems you have outdated sassc, which distribution are you running on?

btw in the latest oomox version you can just put some images to ~/.config/oomox/colors/ directory to generate themes from images right in the oomox gui without installing additional apps

**Comment by wilberanderson** [comment]
Ok, I finally purged Oomox, sassc and libsass through apt and reinstalled oomox only, letting it install the others as dependencies. After this, it worked again.

Issue closed.
