### ISSUE TITLE
Oomox dependencies need to specify libsass0 versions aswell as sassc

### ISSUE THREAD

**Issue by smurphos** [actionless/oomox#133]
Hi,

Can you add `libsass0>v3.4` explicitly as an Oomox dependency in relation to Ubuntu based distros?

Reason - 

In a xenial based distro I installed `sassc 3.4.5` via a .deb download from  [the bionic package page](https://packages.ubuntu.com/bionic/sassc). It installed fine - there is no version requirement attached to it's dependency on `libsass0` which is at version `3.3.4` in the xenial repo. Oomox deb installs but theme builds fail with this combination of `sassc` and `libsass0`

I then went on to install `libsass0 3.4.8` via a .deb download from [the bionic package page](https://packages.ubuntu.com/bionic/libsass0). It installs fine in xenial and Oomox then works as expected.

You could probably update the README.md as-well to point xenial users towards these pages to get an appropriate `sassc` and `libsass0` version. The artful .deb downloads also work fine.

Cheers.

**Comment by actionless** [comment]
i am feeling like you know better what to do:
https://github.com/actionless/oomox/blob/master/packaging/ubuntu/control#L5

**Comment by actionless** [comment]
to build the package after modiying you can run this script:
https://github.com/actionless/oomox/blob/master/packaging/ubuntu/docker_ubuntu_package.sh

**Comment by smurphos** [comment]
Mmm - you overestimate me. Anyway it doesn't look like you can specify a minimum version? So I don't think including libsass0 would help as it is in the xenial repos at version 3.3.4. Installing the Oomox deb after installing sassc from  elsewhere would still work - it would just pull libsass0 from from the xenial repo.

**Comment by actionless** [comment]
i mean i am not using ubuntu or debian so i don't want to break anything

if you can do the change in the debian `control` file and it will work for you as expected i'll be happy to merge

**Comment by smurphos** [comment]
It won't really help so I think leave it as is. If you want me to draft an update for the Oomox readme and the Oomox GTK readme I can do.

**Comment by actionless** [comment]
no, i've just meant something like you changing `sassc` to `sassc>=3.4` in `control` file, rebuilding package and trying if it still works as expected in your setup

if you have troubles building deb package with docker i can do it from my machine and send you the artifact by mail

**Comment by smurphos** [comment]
Ok, I'll give that a try and see if it works.

**Comment by actionless** [comment]
thanks in advance :smile_cat:

**Comment by smurphos** [comment]
OK - I'm getting errors locating some of the the zesty repos running `docker_ubuntu_package.sh` which I'm not sure how to resolve. I will try again later if it's just a case that those repos are down

```
./docker_ubuntu_package.sh
== Copying to temporary directory...
== Removing unstaged git files:
Sending build context to Docker daemon  14.32MB
Step 1/5 : FROM ubuntu:zesty
 ---> fe1cc5b91830
Step 2/5 : WORKDIR /opt/oomox
 ---> Using cache
 ---> 74f4f1060a6c
Step 3/5 : CMD ["/bin/bash", "./packaging/ubuntu/create_ubuntu_package.sh"]
 ---> Using cache
 ---> 8ca3512fa5be
Step 4/5 : RUN apt update && apt install -y make gettext
 ---> Running in 81a16db99894

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Ign:1 http://archive.ubuntu.com/ubuntu zesty InRelease
Ign:2 http://security.ubuntu.com/ubuntu zesty-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu zesty-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu zesty-security Release
  404  Not Found [IP: 91.189.88.162 80]
Ign:5 http://archive.ubuntu.com/ubuntu zesty-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu zesty Release
  404  Not Found [IP: 91.189.88.161 80]
Err:7 http://archive.ubuntu.com/ubuntu zesty-updates Release
  404  Not Found [IP: 91.189.88.161 80]
Err:8 http://archive.ubuntu.com/ubuntu zestytep 4/5 : RUN apt update && apt install -y make gettext
 ---> Running in 81a16db99894

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Ign:1 http://archive.ubuntu.com/ubuntu zesty InRelease
Ign:2 http://security.ubuntu.com/ubuntu zesty-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu zesty-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu zesty-security Release
  404  Not Found [IP: 91.189.88.162 80]
Ign:5 http://archive.ubuntu.com/ubuntu zesty-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu zesty Release
  404  Not Found [IP: 91.189.88.161 80]
Err:7 http://archive.ubuntu.com/ubuntu zesty-updates Release
  404  Not Found [IP: 91.189.88.161 80]
Err:8 http://archive.ubuntu.com/ubuntu zesty-backports Release
  404  Not Found [IP: 91.189.88.161 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-backports Release' does not have a Release file.
The command '/bin/sh -c apt update && apt install -y make gettext' returned a non-zero code: 100-backports Release
  404  Not Found [IP: 91.189.88.161 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu zesty-backports Release' does not have a Release file.
The command '/bin/sh -c apt update && apt install -y make gettext' returned a non-zero code: 100

```

**Comment by actionless** [comment]
there's indeed no security repo for zesty:
http://security.ubuntu.com/ubuntu/dists/

weird

**Comment by smurphos** [comment]
Zesty has been EOL for a couple of months - maybe Ubuntu have tidied up the repos. I'd did try editing the docker file to pull from artful. It appeared to work but I didn't get a usable deb at the end of it.

**Comment by actionless** [comment]
i pushed a workaround to dockerfile

**Comment by actionless** [comment]
does it working fine for you now?

**Comment by smurphos** [comment]
It runs OK until this stage. Looking at the scripts I should have the built deb in '/oomox/packaging/ubuntu'? It's not there.
```
Step 5/5 : COPY . /opt/oomox/
 ---> 02a7103607cd
Successfully built 02a7103607cd
Successfully tagged oomox_ubuntu_zesty_build_image:latest
rm: cannot remove '/opt/oomox/ubuntu_package/opt/oomox/plugins/theme_oomox/gtk-theme/Docker*': No such file or directory
rm: cannot remove '/opt/oomox/ubuntu_package/opt/oomox/plugins/theme_oomox/gtk-theme/docker*': No such file or directory
```

**Comment by actionless** [comment]
it should be copied to the current working directory from which you runned the script

**Comment by smurphos** [comment]
That was the working directory.

**Comment by actionless** [comment]
that's weird, i've just tried on the clean env it worked, the last part of the log is looking like that:

```
Setting up libldap-2.4-2:amd64 (2.4.44+dfsg-3ubuntu2.1) ...
Setting up libcurl3:amd64 (7.52.1-4ubuntu1.4) ...
Setting up curl (7.52.1-4ubuntu1.4) ...
Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
Processing triggers for sgml-base (1.29) ...
Processing triggers for ca-certificates (20170717~17.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 2b64a2ea38f4
 ---> fd7ba11f93d3
Step 5/5 : COPY . /opt/oomox/
 ---> 6be71ad2ce9e
Successfully built 6be71ad2ce9e
Successfully tagged oomox_ubuntu_zesty_build_image:latest
test -d po || mkdir -p po
xgettext --package-name=oomox --foreign-user -o po/oomox.pot oomox_gui/export_config.py oomox_gui/export_common.py oomox_gui/colors_list.py oomox_gui/__init__.py oomox_gui/preview_terminal.py oomox_gui/main.py oomox_gui/color.py oomox_gui/helpers.py oomox_gui/palette_cache.py oomox_gui/presets_list.py oomox_gui/plugin_api.py oomox_gui/preview_icons.py oomox_gui/gtk_helpers.py oomox_gui/theme_file_parse.py oomox_gui/xrdb.py oomox_gui/plugin_loader.py oomox_gui/config.py oomox_gui/theme_file.py oomox_gui/terminal.py oomox_gui/theme_model.py oomox_gui/preview.py oomox_gui/__main__.py
if test -f po/fr.po; then \
        msgmerge -U po/fr.po po/oomox.pot; \
else \
        msginit -o po/fr.po -i po/oomox.pot; \
fi
............................ done.
msgfmt -o po/fr.mo po/fr.po
for f in po/fr.mo; do \
        l="$(basename "$f" .mo)"; \
        d="./locale/$l/LC_MESSAGES"; \
        mkdir -p "$d" || exit; \
        install -m 644 "$f" "$d/oomox.mo"; \
done
dpkg-deb: building package 'oomox' in 'oomox.deb'.
DEB PACKAGING DONE
oomox_ubuntu_zesty_build
DOCKER DONE
```

**Comment by actionless** [comment]
i found the problem in the install script, however i still have no clue why the file is not there on your setup, mb you didn't pulled the submodules?

**Comment by actionless** [comment]
how it's going?

**Comment by smurphos** [comment]
Success. Deb built. 

* Uninstalled Oomox, `sassc` and `libsass0`. 
* Tried to install Oomox - dependencies not met. 
* Installed `sassc 3.4.5.1` from deb  - `libsass0 3.3.4` was installed from the xenial repo as a dependency. 
* Tried to install Oomox - dependencies not met.
* Installed `libsass0 3.4.8.1` from deb
* Successfully installed Oomox.

**Comment by actionless** [comment]
thanks for your investigations!
