### ISSUE TITLE
all my themes have disappeared with the last update

### ISSUE THREAD

**Issue by saltasatelites** [actionless/oomox#139]
Hello, 
With the latest update, all my variations (about 15) of the default themes have disappeared from oomox. 
Is there any way to recover or import my themes, or downgrade to the previous package to the update? I've been searching for one, but I could not find it anywhere (I use Archlinux). My last alternative would be to copy the codes one by one from my /home but this could be a very hard and slow work...
Any suggestion?
Regards

**Comment by actionless** [comment]
could you check the contents of `~/.config/oomox/colors/` dir?
there is no any code in oomox which removing any old themes on upgrade or anything similar to that, mb for some reason it can't read some of the themes so not displaying them

**Comment by saltasatelites** [comment]
Absolutely empty. All my themes are base 16 (maybe that helps or is only coincidence...)
I copied the files and the base-16 folder from a backup and now they all appear

**Comment by saltasatelites** [comment]
I have reinstalled oomox and obviously it doesn't modify anything in / home. I suppose at some point that folder was deleted by accident. Sorry for making you lose your time
