### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by hotice** [actionless/oomox#15]
Themes generated with oomox don't support Ubuntu Unity, while Numix does. Would it be possible to add Ubuntu Unity support?

**Comment by actionless** [comment]
i am looking on https://github.com/shimmerproject/Numix/tree/master/unity now
but see only svg assets for icons like minimize or maximize

do you have an idea where panel color is defined there? or it's somehow inherited from one of GTK themes?

**Comment by hotice** [comment]
The panel looks ok (seems the color is inherited), the only thing missing is the window buttons. Here's a screenshot of a theme generated using oomox, under Unity (Ubuntu 16.04): http://i.imgur.com/muWggSn.jpg

**Comment by actionless** [comment]
could you check current master now?

**Comment by hotice** [comment]
Now it has proper window buttons in Unity. So now it just needs to recolor them.

**Comment by hotice** [comment]
By the way, themes generated using oomox also have this issue in Unity: 

![image](https://cloud.githubusercontent.com/assets/325449/14522838/390059e0-0239-11e6-9aaa-fd800ca86da8.png)

It happens with indicators (Ubuntu Sound Menu and Messaging Menu, etc.) but also for some application menus (not 100% of the menus though). 

This doesn't occur with the Numix theme (either latest stable or latest git), so it's caused by oomox somehow. Screenshot with Numix git:
![image](https://cloud.githubusercontent.com/assets/325449/14522852/51294ca2-0239-11e6-82b2-3ea50bfe2372.png)

**Comment by actionless** [comment]
thanks for reporting, i'll try to figure out where those colors are set

**Comment by TiZ-EX1** [comment]
That menu issue is happening with me too. I'm on Xubuntu 15.10 which has GTK 3.16.7. Once Xubuntu 16.04 is out, I'll see if it happens there too.

**Comment by hotice** [comment]
Well, Xubuntu 16.04 is out since... a few minutes ago: http://xubuntu.org/getxubuntu/ :D

**Comment by TiZ-EX1** [comment]
Oh snap! I guess I'm gonna back up my laptop and then get that party started.

**Comment by actionless** [comment]
ok, so i'll better wait until you will upgrade :)

what gtk version is there?

**Comment by TiZ-EX1** [comment]
16.04 uses GTK 3.18... fortunately. I was using Arch until 3.20 hit and then I noped back to Xubuntu. I even tried fixing stuff, but there were certain things that just... wouldn't stop messing up. Like Syncthing-GTK refusing to go to the tray on start, Quod Libet showing two entry widgets on the search bar, I could go on. I'm gonna stay where it's safe until some of the kinks are worked out.

**Comment by actionless** [comment]
i was doing few fixes to gtk 3.18 and it was looking almost totally as intended (however i wasn't testing it with Unity)

while 3.20 is still in progress, at least NoteBook widget requires lots of love to make it look like in gtk2 or gtk 3.18

**Comment by TiZ-EX1** [comment]
That reminds me, after I finish my upgrade, I'll send a pull request for my branch; its notebook doesn't look as good as Clearlooks', but it does look good enough to match.

**Comment by TiZ-EX1** [comment]
The issue persists on Xubuntu Xenial, with GTK 3.18.

**Comment by actionless** [comment]
weird, here is the full diff between numix and oomox gtk 3.1{6,8}, i have no idea which of the changes causes that issue in unity: https://gist.github.com/actionless/eb34bacb0af7947870fc0e99137949ec

i am sorta suspecting this code, could anyone check it?
https://gist.github.com/actionless/eb34bacb0af7947870fc0e99137949ec#file-patch_gtk30_scss-diff-L480-L484

**Comment by TiZ-EX1** [comment]
Those lines look totally irrelevant to the problem to me... in any case, I went ahead and removed them and it did nothing.

**Comment by TiZ-EX1** [comment]
Got something here:

```
WC130-TiZ:~$ nm-applet
nm-applet-Message: using fallback from indicator to GtkStatusIcon

(nm-applet:14645): Gtk-WARNING **: Error loading image 'resource:///org/numixproject/gtk/assets/menuitem-checkbox-checked-insensitive.png': The resource at '/org/numixproject/gtk/assets/menuitem-checkbox-checked-insensitive.png' does not exist

(nm-applet:14645): Gtk-WARNING **: drawing failure for widget `GtkCheckMenuItem': invalid matrix (not invertible)

(nm-applet:14645): Gtk-WARNING **: drawing failure for widget `GtkMenu': invalid matrix (not invertible)

(nm-applet:14645): Gtk-WARNING **: drawing failure for widget `GtkWindow': invalid matrix (not invertible)
^Z
[1]+  Stopped                 nm-applet
```
