### ISSUE TITLE
feature request: ability to point oomox-cli from aur package at arbirary color file.

### ISSUE THREAD

**Issue by neeasade** [actionless/oomox#16]
eg if I make a colorfile with same format as those in colors I should be able to do something like `oomox-cli -c /path/to/some/file/`

**Comment by actionless** [comment]
have you tried `oomox-cli /path/to/some/file/` ?

**Comment by neeasade** [comment]
welp

**Comment by neeasade** [comment]
sorry, when I had closed this issue I hadn't tested the above because it looked good but it is not -- the issue is in the PKGBUILD for oomox-git. When you create the wrappers for oomox-gui and oomox-cli and pass in `$@` is is not escaped and so the contents of both end up like so:

``` sh
$ cat /usr/bin/oomox-cli
#!/bin/sh
cd /opt/oomox/
exec ./change_color.sh ""
$ cat /usr/bin/oomox-gui
#!/bin/sh
cd /opt/oomox/
exec ./gui.sh ""
```

escaping those chars in the cat call in PKGBUILD is the fix.

**Comment by neeasade** [comment]
:+1:
