### ISSUE TITLE
feature request: custom PATHLIST

### ISSUE THREAD

**Issue by neeasade** [actionless/oomox#18]
I would like the option to predefine the PATHLIST array (in change_color.sh) if say I were only interested in gtk2 themes -- that way I wouldn't have to deal with gtk3 resources generation runtime if I didn't want too. 

side note: thanks for this project, it's great.

**Comment by actionless** [comment]
i think i'll add an env var for that tomorrow

thanks :)

**Comment by actionless** [comment]
please test this: https://github.com/actionless/oomox/commit/d1273a8db88cf61ccffe902a8c6407ac92609ec5

**Comment by neeasade** [comment]
Excellent, works.
