### ISSUE TITLE
Can't select theme in MATE desktop appearance tool

### ISSUE THREAD

**Issue by kajzersoze** [actionless/oomox#24]
Running Gentoo, installed all the deps, launched gui.sh, everything is fine, no error messages...
However, the only listed themes are those in the colors folder from oomox main folder.
It doesn't see themes from /usr/share/themes and .themes from /home folder.
That's the first problem.

Second problem is that even if I start working from a theme that is listed, say Numix for example, I first clone it then do some changes and then export it. Theme appears in the .theme folder, looking at that folder everything looks fine, like any other theme, but I don't see it when I want to change the theme.
It's not listed.
Using Mate btw.

Any hints ?

**Comment by actionless** [comment]
it's more a problem with documentation

colortheme is not gtk theme,
in `./colors/ and `~/.config/oomox` there are colorschemes

when you generate a Numix derivation with the selected colorscheme, gtk theme is being exported to `~/.themes/`


in UI "Save button" saves colorscheme itself, but "Export" button saves gtk scheme based on the current colorscheme

**Comment by kajzersoze** [comment]
Okay, that solves the first problem, I get that part now.

But when I export gtk theme to ~/.themes/ it's not listed in the Appearance where I change themes.
I see Makefile in that exported theme folder, what's that for ?

**Comment by actionless** [comment]
what appearance tool do you use? could you try using `lxappearance`?

**Comment by kajzersoze** [comment]
Appearance tool from Mate desktop.

I guess I can install lxappearance but I don't see why there would be any difference.

**Comment by actionless** [comment]
it's a part of the debugging process :)

mb it not shows up in mate tool because missing some theme meta file required in that DE

at the moment i personally tested it only with `lxappearance`

**Comment by kajzersoze** [comment]
It doesn't appear because you don't have this in [X-GNOME-Metatheme] section of index.theme file :

```
IconTheme=gnome
CursorTheme=adwaita
CursorSize=24
```
Then it shows, but there are other issues, you name exactly the same each theme "Oo-mox" , also for other things as well , like this :
```
Name=Oo-mox
GtkTheme=Oo-mox
MetacityTheme=Oo-mox
```

So for example if I clone Base-16/Google-Dark and name it "Google"  it's not gonna be "Google" but "Oo-mox" , and if I select it it wouldn't work because there's no gtk theme "Oo-mox"
Same happens if I don't clone it but Export some preset straight away.

**Comment by actionless** [comment]
@kajzersoze please try with 320a0df

**Comment by chrisnovakovic** [comment]
As of  05c862c, generated themes still don't appear in the MATE Appearances applet. `index.theme` is missing the `IconTheme` key in the `[X-GNOME-Metatheme]` section: without that key the theme won't be listed, regardless of whether the given icon theme actually exists (the value can even be left blank, but the key has to exist).

**Comment by actionless** [comment]
please check if this helps: https://github.com/actionless/oomox/commit/7754eee5191356e5fc123650aec33a1d68be05e5

**Comment by chrisnovakovic** [comment]
Yep, `7754eee` fixes this: generated themes now at least appear in the MATE Appearances applet.

**Comment by actionless** [comment]
>at least

is something still not working?

**Comment by kajzersoze** [comment]
Sorry for late reply, working great now !
