### ISSUE TITLE
Files toolbar buttons in Unity are mismatched

### ISSUE THREAD

**Issue by vitalykorolev** [actionless/oomox#25]
The buttons end up being light on a dark background unlike the original theme.
![image](https://cloud.githubusercontent.com/assets/1957746/14992544/58e8fdd4-111b-11e6-98a7-58a22222c27f.png)

**Comment by actionless** [comment]
it was done on purpose

**Comment by vitalykorolev** [comment]
Interesting. Perhaps this could be option in the UI to have it either way?

**Comment by actionless** [comment]
yup it's doable, I will also have to change Edit pane a bit to support not only colors but bools

but generally i am agree, for some colorschemes those headerbar buttons are not working visually when it's so contrast (like on yours example)

could you propose a shortname for this option?

**Comment by vitalykorolev** [comment]
If you draw it on the preview, then whatever the option is called the change would be visible and clear.

**Comment by actionless** [comment]
true

so i have to start with improving the preview -- atm it's missing lots of other widgets too

**Comment by actionless** [comment]
try with this: https://github.com/actionless/oomox/commit/b8b7c0f43f47e844525fae7b14ebd0cf6c18fd4e

**Comment by vitalykorolev** [comment]
I tried today's release and buttons in a dark theme are still broken. Specifically, light toolbars are getting dark buttons and dark toolbars have two variations of the dark buttons as you can see in the screen shot. I make the foreground text red to see which button would pick up the color. (HDR_BTN_FG)

![image](https://cloud.githubusercontent.com/assets/1957746/15303018/a2316554-1b6a-11e6-9253-a37ea6147d5d.png)

**Comment by actionless** [comment]
it looks like GTK+ 3.1{6,8} theme have to be updated, i fixed that only for GTK+ 3.20

feel free to contribute to the legacy theme variant

**Comment by actionless** [comment]
gtk 3.16 is not supported anymore
