### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by jamesbvaughan** [actionless/oomox#27]
In the css rules that fix problems with tiling WMs, you included this
```
window decoration {
    margin: 0;
}
```

Is that correct or is it supposed to be something like `.window-decoration`?

Thank for making this!

**Comment by actionless** [comment]
in GTK+ 3.20 it's correct, however idk about the previous versions

**Comment by jamesbvaughan** [comment]
Okay, cool. I was just checking.

Thanks!
