### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by nadehi18** [actionless/oomox#28]
So I just dowloaded the project which is awesome btw, but when I try to execute the gui.sh script I get this error: http://pastebin.com/zpiGjpqx  I'm decent with python but not that good, so it appears to be something to do with the theme.css file.

**Comment by actionless** [comment]
which GTK+3 version do you use?

**Comment by nadehi18** [comment]
3.10.8-0ubuntu1.6
when I run dpkg -s libgtk-3-0|grep '^Version'

**Comment by nadehi18** [comment]
Actually, are the colors in the theme files just normal ones used in html and the like (can't think of what they're called atm) cause in that case I'll just hard code a theme and not even worry about the gui...

**Comment by actionless** [comment]
if you are using older GTK+ version the theme won't work for you, it requires at least 3.16, unfortunately i haven't marking releases with supported GTK+3 version, so now i can't recall which of the older versions do you need in order to get it work

**Comment by nadehi18** [comment]
I figured, but I'm mainly using it for the spotify customization, so I just
made the colors match my Gtk+ theme and it works,  it's actually a real
pain to update to Gtk+ 3.20 on ubuntu, so that's why I gave up.  This is
why I'm going to transition to arch when I have time to do so.
