### ISSUE TITLE
Xfce panel is not being recolored

### ISSUE THREAD

**Issue by haarp** [actionless/oomox#31]
Hi,

nice tool. When I use or modify Numix, the Xfce panel is looking a bright ugly greyish white. Most other themes have the same result. Is it possible that this color is missing from the gtk2 theme?

**Comment by actionless** [comment]
i am not using xfce so can't say for sure, mb later on i will install it to VM to adjust a theme for it

i will appreciate if you'll submit a PR with fix if you'll find the problem

**Comment by friederbluemle** [comment]
Any updates on this? :)

**Comment by actionless** [comment]
i am still not using xfce, sorry

if you like to get it solved i can help you with doing the fix and you can do a pull request then

**Comment by haarp** [comment]
I've tried Oomox again today with xfce4-panel-4.12.0. Different themes color the panel differently. I suppose this is fixed now! :)

**Comment by actionless** [comment]
good to hear, thanks for making an update!

mb they moved the panel to gtk3 so that resolved the problem
idk which gtk version that panel is using i can't figure it out without installing:
```
$ pacman -Si libxfce4ui
<....>
Depends On      : libxfce4util  gtk2  gtk3  xfconf  libsm  startup-notification
```

**Comment by haarp** [comment]
xfce4-panel can be built against GTK3 since 4.12.0, but it retains some GTK2 dependencies. That must've made the difference.

**Comment by dbeckwith** [comment]
I am having this problem. I duplicated the numix theme and just changed the highlight colors, but when I apply the new theme it turns my panel light gray. I have xfce4-panel 4.12.0. I notice other themes can change the panel color, but I guess copying numix reset it somehow? How do I set the panel color back to what it was in the theme?

**Comment by actionless** [comment]
@dbeckwith you could try to make diff of your modified theme and the generated one to see from which part of config that gray color is coming

**Comment by dbeckwith** [comment]
Is there a specific file I should diff? I'm not really sure how the theme folders are structured and diffing the entire folder didn't really help, there are a lot of differing files.

**Comment by dbeckwith** [comment]
I was able to change the panel background color by editing gtk-2.0/gtkrc, but the panel text is still dark and has a weird light selection highlight. I think at this point I might just copy the original Numix theme and try to modify the highlight colors from that.

**Comment by dbeckwith** [comment]
Yeah I just edited the Numix theme gtk-2.0/gtkrc and that worked for me. Still curious why oomox's copy of Numix messes up the panel colors though.

**Comment by actionless** [comment]
so since editing that file is causing your panel to change the color then `gtk-2.0/gtkrc` is the one in which you need to make a diff to try finding from where that gray color is coming
