### ISSUE TITLE
Invalid CSS after "...ant == "dark", ": expected function argument, was "#%FG%, #%BG%

### ISSUE THREAD

**Issue by bodqhrohro** [actionless/oomox#32]
bodqhrohro@localhost:/opt/oomox$ make
    rm -rf gtk-3.0/dist
    rm -f gtk-3.0/gtk.gresource
    rm -rf gtk-3.20/dist
    rm -f gtk-3.20/gtk.gresource
    scss --update --sourcemap=none gtk-3.0/scss:gtk-3.0/dist
      directory gtk-3.0/dist
          error gtk-3.0/scss/_global.scss (Line 6: Invalid CSS after "...ant == "dark", ": expected function argument, was "#%FG%, #%BG%);")
          error gtk-3.0/scss/_global.scss (Line 6: Invalid CSS after "...ant == "dark", ": expected function argument, was "#%FG%, #%BG%);")
    Makefile:17: ошибка выполнения рецепта для цели «css_gtk3»
    make: *** [css_gtk3] Ошибка 1
    bodqhrohro@localhost:/opt/oomox$ apt show ruby libgdk-pixbuf2.0-dev libxml2-utils python3-gi gtk2-engines-murrine|grep Version

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

    Version: 1:2.3.0+4
    Version: 2.34.0-1
    Version: 2.9.3+dfsg1-1
    Version: 3.20.1-1
    Version: 0.98.1.1-5
    bodqhrohro@localhost:/opt/oomox$ gem specification sass|grep '^  version:'
      version: 3.4.22

**Comment by actionless** [comment]
it's not the correct way to use, please refer to the readme

that's not an actual makefile, but a template which is getting filled by change_color.sh
