### ISSUE TITLE
Make border color configurable

### ISSUE THREAD

**Issue by TiZ-EX1** [actionless/oomox#34]
Okay, so I'm working on a branch that adds optional colors. Since we have a stylistic difference of opinion on what tab colors should be, I figured I might as well make it configurable, and make it optional.

Anyways, I was lagged a long while behind and did a rebase today, exported my theme to make sure it still looks right, and now the borders on GTK2 are btn_fg mixed with btn_bg. I know you don't really use dark themes yourself. At least I think I remember you saying that? Anyways, I do, and I have to say that I am not a fan of this change.

There's not really a forum to discuss stuff like this, so all I could think to do is open an issue. It looks good on that LCARS dark theme in the screenshot, but that's because it's a light button background and a dark foreground, and since that dark foreground is roughly the same as the regular background, the mix creates a nice even contrast. My buttons are slightly less dark on dark, with light foreground. It's glaring and I'm not a fan. If I may propose an alternative, mix normal_bg and button_bg instead, and shade it 0.8. It should yield roughly the same effect that you have now on that LCARS theme without rendering dark on dark ugly. Is there anyone else using dark schemes with oomox that can offer perspective?

Also, I noticed it was inconsistent with 3.18, and saw that you have basically stopped updating the 3.18 version of the theme. Ubuntu's LTS is on 3.18, which means that there are people who will not be upgrading to 3.20 or further for the foreseeable future. Do you need a 3.18 maintainer?

**Comment by TiZ-EX1** [comment]
While we're talking I'll make a branch and try out how my proposed change looks.

**Comment by actionless** [comment]
> Okay, so I'm working on a branch that adds optional colors. Since we have a stylistic difference of opinion on what tab colors should be, I figured I might as well make it configurable, and make it optional.

i like the idea to have more options

>Anyways, I was lagged a long while behind and did a rebase today, exported my theme to make sure it still looks right, and now the borders on GTK2 are btn_fg mixed with btn_bg. I know you don't really use dark themes yourself. At least I think I remember you saying that? Anyways, I do, and I have to say that I am not a fan of this change.

feel free to prepare a change to make the behavior optional or to make border color editable the same as other colors

> Also, I noticed it was inconsistent with 3.18, and saw that you have basically stopped updating the 3.18 version of the theme. Ubuntu's LTS is on 3.18, which means that there are people who will not be upgrading to 3.20 or further for the foreseeable future. Do you need a 3.18 maintainer?

yes, i will be happy if you could maintain it

**Comment by TiZ-EX1** [comment]
Actually, I can't maintain it. I should have been more careful with my wording, I didn't mean to imply that I could step up. Full-time job, summer classes, and competitive gaming own my life right now. I'm really sorry about that.

**Comment by actionless** [comment]
closed in prior to #70
