### ISSUE TITLE
base16-builder use

### ISSUE THREAD

**Issue by Luke-Nukem** [actionless/oomox#35]
Great tool, thanks for making it. I created some [templates](https://github.com/base16-builder/base16-builder/pull/112) for the [base16-builder](https://github.com/base16-builder/base16-builder) tool to output oomox format.
Perhaps you would like to use this to dump the base16 range in to oomox? A quick python script makes it easy (just missing the 3024 theme). Run it in the base16-builder directory after building.
```
#! /bin/env python3
import os

colours = ["apathy", "ashes", "atelier-cave", "atelier-dune", "atelier-estuary", "atelier-forest", "atelier-heath", "atelier-lakeside", "atelier-plateau", "atelier-savanna", "atelier-seaside", "atelier-sulphurpool", "bespin", "brewer", "bright", "chalk", "codeschool", "colors", "darktooth", "default", "eighties", "embers", "flat", "gooey", "google", "grayscale", "greenscreen", "harmonic", "hopscotch", "irblack", "isotope", "macintosh", "marrakesh", "mocha", "monokai", "oceanicnext", "ocean", "oliveira", "paraiso", "phd", "pop", "railscasts", "seti", "shapeshifter", "solarized", "summerfruit", "tomorrow", "tube", "twilight", "yesterday-bright", "yesterday-night", "yesterday"]

light_command = "./dist/cli.js -s {0} -t oomox -b light > ~/.config/oomox/colors/Base-16/{1}-Light"
dark_command = "./dist/cli.js -s {0} -t oomox -b dark > ~/.config/oomox/colors/Base-16/{1}-Dark"

for name in colours:
    Name = ""
    try:
        Name = name.capitalize()
    except:
        Name = name
        
    light = light_command.format(name, Name)
    os.system(light)
    dark = dark_command.format(name, Name)
    os.system(dark)
```

**Comment by actionless** [comment]
is that makes any sense now since your change to base16-builder was merged?

**Comment by Luke-Nukem** [comment]
@actionless it's good to have my changes merged to base-16 so other people can modify the templates, but not everyone will want to use the base16-builder tool as it is npm based. If you would like it, I can push all the oomox format themes to you.

**Comment by actionless** [comment]
ah, you mean to import themes, not to have ability to import them in oomox application?

i don't mind to add more themes

**Comment by Luke-Nukem** [comment]
Okay, I'll check that everything is working okay then push them in.

**Comment by actionless** [comment]
ok, thanks
