### ISSUE TITLE
Problems with the gi-module and python3 when trying to launch oomox-gui

### ISSUE THREAD

**Issue by joelostblom** [actionless/oomox#38]
Hi,
I'm running Antegros (an arch derivative) and after I install `oomox-git` from AUR, I can't launch `oomox-gui`. First, I get an error about missing the `gi`-python module. After installing that, there is an issue with the file `anaconda3/lib/python3.5/site-packages/gi/__init__.py `, where the python2 print-syntax is used. I tried changing that to the python3 syntax manually, but then I run into this issue

```python
  File "/opt/oomox/gui/main.py", line 4, in <module>
    gi.require_version('Gtk', '3.0')  # noqa
AttributeError: module 'gi' has no attribute 'require_version'
```

I created a virtualenvironemnt with python2 and installed and ran `oomox-gui` from there, but it still picked up my python3 environment. I could not find a python3 version for the `gi`-module. What can I do to get `oomox-gui` up and running?

**Comment by actionless** [comment]
GUI compatible only with python3

`gi` should be in `python-gobject` package in Arch, guess in Antegros it's the same.

Try running it manually, go to the oomox directory and `python3 -m gui`

If you are wanna use virtualenv for some reason, make sure you've created it with `--system-site-packages` option since that's needed for using `gi`

**Comment by joelostblom** [comment]
I do have `python-gobject` installed, but it seems like my anaconda python installation can't detect it. Navigating to the directory and running `/usr/sbin/python3 -m gui` worked, thanks!

**Comment by artemisclyde** [comment]
I have python installed globally on my system and in anaconda.
I could also not start the gui, so I deleted the anaconda path from my $PATH variable, now it works!
