### ISSUE TITLE
Is it possible to change the color of the line between the header bar and the menu bar?

### ISSUE THREAD

**Issue by joelostblom** [actionless/oomox#40]
Is it possible to change the color of the line between the header bar and the menu bar, indicated by the arrow in this screenshot? I tried all the options in the gui, but none seemed to affect that line.

![selection-20160623-01](https://cloud.githubusercontent.com/assets/4560057/16315139/0b2491ce-394f-11e6-86a7-c65e1ac4fe45.png)

**Comment by actionless** [comment]
could you check the same theme with `gtk3-widget-factory` and post the screenshot?
i suspects that's a bug in preview

**Comment by joelostblom** [comment]
Sorry, I am not sure how to use `gtk3-widget-factory`. Do I need to export the theme from oomox? I get a message "Sorry, something went wrong", when trying to export any theme.

The line shows up in all of themes that are available to me by default in oomox, so it is not specific to theme I created for testing. Do you also see this line in the default oomox themes?

**Comment by actionless** [comment]
yes, you need to export it first before viewing in widget factory.

could you copy the log? have you installed all the required dependencies? i suspect `scss` is missing

**Comment by actionless** [comment]
feel free to re-open
