### ISSUE TITLE
Glitched border on xubuntu

### ISSUE THREAD

**Issue by luismercado** [actionless/oomox#41]
The color schemes are working fine, but the window decoration are glitched with a white border with some parts dotted others just plainly glitched. every expoerted theme behaves the same. I'm attaching a screenshot.

![screenshot_2016-06-30_17-07-23](https://cloud.githubusercontent.com/assets/20233577/16508279/584b3e16-3ee6-11e6-9ad7-63de2110fbab.png)

**Comment by actionless** [comment]
could you try it with reverting this commit https://github.com/actionless/oomox/commit/d56cbd8ea37ac1311b83269d8b99260d7a126607 ?

**Comment by actionless** [comment]
feel free to reopen

**Comment by FcoRTendero** [comment]
Hi, same issue here using xfce. I reverted d56cbd8 commit resizing those icons to 24x24 but it did not solve the problem

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#10
