### ISSUE TITLE
Serious graphical glitches in syntaptic and gdebi etc..

### ISSUE THREAD

**Issue by HerborenInVlammen** [actionless/oomox#44]
The last two versions of oomox (installed via ppa) has created themes with some serious glitches in the installation dialogues used by synaptic and gdebi, and possibly other apps.  There is also several error message about missing clearlooks...  etc..
[oomoxbug.mkv.zip](https://github.com/actionless/oomox/files/534317/oomoxbug.mkv.zip)

Occurs 100% of the time when using the above apps and a theme created by the last two vesions of oomox.  Install an app using synaptic for example, and if in the installation (not download) phase of an app one clicks the "details" triangle within the dialoge and a terminal window is opened the glitches and error messages can be clearly seen.

Note that switching to a non oomox created theme (or oomox theme prior to the last to releases) and the issue goes away.

This is on Xubuntu Xenial up-to-date and using oomox 0.24.0-1 (the issue started in previous version).

I have recorded a screen cast of the issue so you may see exactly the issue, and read the error messages within the terminal window.  It is in the attached ZIP file.

**Comment by actionless** [comment]
can you reproduce the issue with the latest Numix version?

**Comment by HerborenInVlammen** [comment]
How can I get the latest version?

**Comment by actionless** [comment]
https://github.com/numixproject/numix-gtk-theme

**Comment by HerborenInVlammen** [comment]
Thanks.  The version from Git does NOT exhibit the problem when used as
the active theme.

However, the latest version is unusable (see screen shot of synaptic
using the latest Numix) as a theme as it completely looks as if it is
for a later version of GTK than 3.18 even though it says 3.18 is the
min. required. 

Note that I have now discovered that the problem exists using the Xenial
repo version of Numix as the active theme.  It does not exist for
Greybird, Adwaita, Arc, Vertex etc..  Obviously a Numix issue. 

Sorry to be a pain.  I know little about this subject

**Comment by actionless** [comment]
i guess you have to stick with https://github.com/actionless/oomox/releases/tag/0.22.0 while waiting for you distro to update GTK+ version
