### ISSUE TITLE
Change color of the bar when click

### ISSUE THREAD

**Issue by holmeslinux** [actionless/oomox#46]
hi,
congratulations on the creation of oomox is excellent...
i am creating some themas.
i would like to know how to change the color of the bar when you click, see image

http://www.auplod.com/u/adpulo896c6.png

vlw fwi, Holmes :)

**Comment by actionless** [comment]
that's a mix of menubar bg and fg colors:
https://github.com/actionless/oomox/blob/master/src/gtk-3.20/scss/widgets/_menu.scss#L29

**Comment by holmeslinux** [comment]
@actionless 
hi,
i did not understand! i need to edit the file?

vlw fwi, Holmes :)

**Comment by actionless** [comment]
yes

all the colors are generated from the theme variables (by mixing them together or lightening/darkening them), you can use selected_bg there

**Comment by holmeslinux** [comment]
hello,
a doubt: i have to remove the line
 
**background-color: mix($menubar_bg_color, $menubar_fg_color, .21);**

vlw fwi, Holmes :)

**Comment by actionless** [comment]
in that case menus background won't be changing the color at all

**Comment by holmeslinux** [comment]
hello,
then, i do not understand...
this line is in the file, but the manipulation of color can not change the background color of the menu when i click.
you need to do to change the color?

vlw fwi, Holmes :)

**Comment by actionless** [comment]
you have to re-generate your theme after change to SCSS
