### ISSUE TITLE
Still getting the "Gtk-WARNING **: Unable to locate theme engine in module_path: "clearlooks"," message.

### ISSUE THREAD

**Issue by HerborenInVlammen** [actionless/oomox#48]
Even after upgrading to GTK 3.20.2.1, I am still getting the following message in the terminal output of a Synaptic or Gdebi install on themes generated with Oomox 0.24.1-1:

Gtk-WARNING *_: Unable to locate theme engine in module_path: "clearlooks", at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 96, <> line 1.
Gtk-WARNING *_: Unable to locate theme engine in module_path: "clearlooks", at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 96, <> line 1.
Gtk-WARNING *_: Unable to locate theme engine in module_path: "clearlooks", at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 114, <> line 1.
Gtk-WARNING *_: Unable to locate theme engine in module_path: "clearlooks", at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 114, <> line 1.

This does not occur with Numix 2.6.4-1.

Using Xubuntu Xenial all up-to-date and XCFE of course.

(Regarding issue 44, upgrading to GTk 3.20 fixed that).

**Comment by actionless** [comment]
It seems like a warning about gtk2 theme.

There is one related difference between Numix and Oomox here -- the latter is using `clearlooks` engine for drawing notebook tabs.

I suspect during upgrade the package containing clearlooks engine (in archlinux it's `gtk-engines`) got lost.

**Comment by HerborenInVlammen** [comment]
No, this only started occurring_with the upgrade to oomox 0.23.x.x_ so
occurred /before/ I upgraded to GTK3.20.  Also, I have two clearlooks
themes (Perfection and Phenix) installed and do not give the message
when they are active.... only with Oomox.  One would think if the
clearlooks engine was missing then themes made for it would announce
that .... Correct?

It really is nothing to worry about as I cannot seem to find any
negative results because of it, but just so you know, since using themes
generated by oomox 0.23 and later I am also getting "missing clearlooks"
messages when I launch some GUI apps from a terminal (Exfalso,
Quodlibet, Libreoffice, and others).  Here is the message:

Gtk-WARNING **: Unable to locate theme engine in module_path: "clearlooks",


Changing to another non-oomox generated theme and the message does not
appear.  From a layman, but long-time Linux user, it really is related
to Oomox IMO as no other theme including other Numix based themes
exhibit this message, and it began with oomox 0.23 and later.

**Comment by actionless** [comment]
So, if you will generate now the theme from oomox 0.22 the problem is still reproducing?

**Comment by actionless** [comment]
feel free to reopen if you are still able to reproduce the issue
