### ISSUE TITLE
Latest version of oomox still generating "Clearlooks Engine Missing" messages

### ISSUE THREAD

**Issue by HerborenInVlammen** [actionless/oomox#51]
Sorry to not respond to your replies sooner ... was out of country.

Anyway, the missing clearlooks engine issues still exists with ALL oomox generated themes on Ubuntu based OS'.

I have confirmed this on the latest Peppermint OS (Ubuntu based) as well.  I do not have any other Linux OS to try it on, but it is definitely an Oomox issue... Why?  

1) Because it only appears on Oomox generated themes; 
2) It appears 100% of the time
3) It started with Oomox 0.23 and has continued with each new version since
4) It can be replicated 100% of the time on another Ubuntu based OS other than Xubuntu Xenial.

As I mentioned before the themes display OK, but the message shows up in terminal windows when apps are launched from said windows.

**Comment by actionless** [comment]
it seems ubuntu by default is missing clearlooks gtk2 engine:
https://github.com/GNOME/gtk-theme-engine-clearlooks

you need to install it to have gtk2 version of the theme to work

**Comment by HerborenInVlammen** [comment]
No, that is not the problem.  I have two Clearlooks GTK 2&3 themes
installed from the repos... they work fine. As well, NO OTHER NUMIX
based theme is asking for it; as a matter of fact, no other theme PERIOD
is asking for it.  Nor have they asked for it... until Oomox 0.23 and
later.  Just themes generated by Oomox are effected.  Your software.  No
other.  Generated by your software.  No other.

Also, do you really think that sending me to a link that is 6+ years old
is really the solution?  Come on guys.  It was introduced with 0.23 of
Oomox.  If it was as you say, a Clearlooks gtk2 engine missing issue, it
would have been showing from the get go and even the noobiest of noobs
can see that. So, I now know that you do want to acknowledge this as
being an Oomox problem, but it is pretty obvious from this end that it is.

I have brought this bug up three times now and so far you have sluffed
it off as 1) A Numix core theme problem:  Solution:  Upgrade to latest
Numix.  Cured issue? No.  2) A GTK3 problem: Solution, upgrade to
GTK3.2x.  Cured issue: No; and now 3) a Clearlooks engine missing
issue.... and you send to me clearlooks from 2011????  An engine that I
cannot even begin to install even if I wanted to because it would break
the existing INSTALLED Clearlooks engine?

Pretty lame. 

You initiated this bug into Oomox 0.23.  And, if you had actually been
paying attention to what I wrote .... and it is obvious you have not,
then you would know*it is a bug in Oomox*.  I even sent you videos
displaying it and you still are not acknowledging it to be a problem
with your app even though 1) It was introduced in Oomox 0.23, and 2) It
only shows up under themes generated by Oomox, and 3) .  Pretty lame
guys....!!

Seriously!  You suggest I try and install a theme engine from 6+ years
ago??? Do you even use Linux?

Again .... pretty lame guys!

**Comment by HerborenInVlammen** [comment]
The site you sent for Ubuntu is 6+ years old. ... Nuff said....

Anyway, thanks for trying.
