### ISSUE TITLE
Oblogout: Remove the highlighting from the buttons

### ISSUE THREAD

**Issue by holmeslinux** [actionless/oomox#52]
hi guys
i made a theme using oomox and i'm using oblogout. i would like to remove the highlighting from the buttons. see:

http://www.auplod.com/u/pudloa8af6c.png

i think it should have a relationship with gtk (2, 3,0 and 3,20), but i could not find where to remove it.
does anyone have any ideas?

vlw fwi, Holmes :)

**Comment by actionless** [comment]
btw i would also suggest creating the same question in ObLogout community too

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#3
