### ISSUE TITLE
Failed to load checkbox-checked-dark.svg

### ISSUE THREAD

**Issue by eti0** [actionless/oomox#55]
![2017-01-17-00 02 32](https://cloud.githubusercontent.com/assets/14180792/22001938/68a10552-dc48-11e6-9f1a-a36c5498c09a.png)

As seen in the picture above, I have no idea where this issue comes from, using the latest release from the AUR (oomox-git).

**Comment by actionless** [comment]
1) try checking if that file and symblink to its directory were installed by the package manager:
```sh
$ pacman -Ql oomox-git | grep assets/checkbox-checked-dark.svg
oomox-git /opt/oomox/src/assets/checkbox-checked-dark.svg
$ pacman -Ql oomox-git | grep gtk-3.20/assets
oomox-git /opt/oomox/src/gtk-3.20/assets
```

2) check if it's still in your filesystem:
```sh
$ ls -ls /opt/oomox/src/gtk-3.20/assets/checkbox-checked-dark.svg
```

3) try opening that file with a general image viewing application

**Comment by eti0** [comment]
After further analyse it seems that the issue only occurs on my side.
I'll find a way to fix it but it seems like it's an icon cache issue.
