### ISSUE TITLE
Titlebar color issue with GTK 3.20 (Unity)

### ISSUE THREAD

**Issue by hotice** [actionless/oomox#61]
In Ubuntu 16.10 (with Unity) / GTK 3.20, non-CSD apps have a border around the titlebar, which looks pretty weird:

![image](https://cloud.githubusercontent.com/assets/325449/23120647/e11a8066-f765-11e6-8df4-d579ed9645f5.png)

There's also a border in Ubuntu 16.04 (GTK 3.18), but it's gray and doesn't look out of place:

![image](https://cloud.githubusercontent.com/assets/325449/23120653/e7554560-f765-11e6-8d37-11cdc6c4fa72.png)

This occurs for some time (wasn't introduced with version 1.1.0), but I haven't used themes generated with newer Oomox versions in a while.

**Comment by actionless** [comment]
could you please check which of those three values is causing the problem?

`wm_bg`, `wm_border_focused`, `wm_border_unfocused`

https://github.com/actionless/oomox/commit/6e4bd77e58d81a80e6910cd6524f219186be9d97#diff-faf711dcbb129837a5ce75f5dad2d795R99




in a built theme you can replace them in `gtk-3.20/dist/gtk.css` on lines `85`-`87`

**Comment by actionless** [comment]
i've just re-checked in GNOME 3.22, there borders behave as supposed (around all the window, not only titlebar)

mb to make those border optional in oomox theme settings?

**Comment by hotice** [comment]
I changed all 3 and nothing changed in the theme for some reason (and yes, I changed to some other theme, then back to this one). By the way, it only happens for focused windows. Unfocused windows are not affected.

An optional border would be nice, yes.

**Comment by actionless** [comment]
as you can see from the blame[1] i haven't changed anything else, so the problem should be about border_focused

could you do few more attempts, are you sure you were changing the file in `dist` directory, not source scss file?


[1] https://github.com/actionless/oomox/blame/6e4bd77e58d81a80e6910cd6524f219186be9d97/src/gtk-3.20/scss/_global.scss

**Comment by hotice** [comment]
I don't know why directly editing that didn't work. But anyway, I then set ``wm_border_focused`` to ``transparent`` directly in the Oomox source, generated a new theme and it worked, the colored border is no longer present.

**Comment by actionless** [comment]
@hotice please try with the latest commit i referenced above

**Comment by actionless** [comment]
@hotice or you could write me on some messenger, because i also need to investigate one other unity issue

**Comment by hotice** [comment]
@actionless The latest commit fixes the issue. 

Regarding other things to test, I'm at work and can't use messengers (I can on my phone but that's not very productive). But let me know what you need to test and I'll do it as soon as I can.

**Comment by actionless** [comment]
this issue: https://github.com/actionless/oomox/issues/26

**Comment by hotice** [comment]
I'm not sure what you need me to do, so exact instructions would help...

**Comment by actionless** [comment]
see the conversation from here, https://github.com/actionless/oomox/issues/26#issuecomment-256325133

please check if doing that one replacement in unity template is enough for theme to display correctly there

**Comment by actionless** [comment]
i tried to replace the colors without seeing the result, check this: https://github.com/actionless/oomox/commit/f216a5c2e155763a8ba4605558be475baf58ffcd

**Comment by actionless** [comment]
i committed more on master

**Comment by hotice** [comment]
It works great for me. Here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/325449/23157493/2b457178-f824-11e6-92a2-dd2653da5f28.png)

![image](https://cloud.githubusercontent.com/assets/325449/23157497/2fd970ae-f824-11e6-91bb-35e3674adad4.png)

![image](https://cloud.githubusercontent.com/assets/325449/23157501/335077c8-f824-11e6-9eab-b37b3bad5ae8.png)

![image](https://cloud.githubusercontent.com/assets/325449/23157506/36a13746-f824-11e6-8774-3a1eeab61591.png)

Unrelated, but I'll ask here. Numix and thus, Oomox, removes the Unity Launcher icon background which some don't like. Would it be possible to add an option for this? That would make it so much more appealing for some. Here is a screenshot with the Unity Launcher when using a theme generated by OOmox:

![image](https://cloud.githubusercontent.com/assets/325449/23157549/69acd726-f824-11e6-8a2a-f899286fe03c.png)

And with the default style, used by every other theme:

![image](https://cloud.githubusercontent.com/assets/325449/23157567/77303154-f824-11e6-9c0f-35da486ee456.png)

**Comment by actionless** [comment]
thanks for testing!

regarding unity icons' decorations:
i can add options in script and GUI if somebody will prepare right SVG assets for the theme

**Comment by hotice** [comment]
I was just saying not to remove the default style (I really don't know why the Numix devs did that)...

**Comment by actionless** [comment]
have you tried if the theme displays as you expect if you are removing numix assets with those backgrounds from ./unity directory of the generated theme?

**Comment by hotice** [comment]
I removed all the unity/launcher*.svg from the generated theme and now the Launcher looks ok:

![image](https://cloud.githubusercontent.com/assets/325449/23163609/c220a5ce-f83b-11e6-93c8-4f2dba34d471.png)

**Comment by actionless** [comment]
so, to clarify, you want an option which will be removing/not copying all the files matching `unity/launcher*.svg`, no other modifications need to be made to solve it?

then it's quite easy to do

**Comment by actionless** [comment]
option can be `Unity launcher background:   (Numix|Classic)`

**Comment by hotice** [comment]
Yes!

**Comment by actionless** [comment]
good, i will try to find few minutes during this week to arrange everything
