### ISSUE TITLE
Make border and oultine widths configurable

### ISSUE THREAD

**Issue by cwendling** [actionless/oomox#70]
Ideally in complement with #34, it would be highly useful to make the border width and outline width configurable, especially for accessibility purposes (e.g. people with disabilities, particularly visual).

The part for borders is not totally straightforward, but seems still fairly easy: replacing all border width values with a configurable value.  As is, the default would be 1px.  This would be mostly good I guess, and only a very few places require special care like multiplying, but that's probably fine.

However, the outline-width part seems a lot trickier than I expected: just altering `outline-width` and `outline-offset` with the border width works, but it starts to visually overlap the outlined content very quickly (already at values of 2).  I guess carefully playing with margins or alike to compensate would work, but I'm really not sure, and even less so where to do so.  Of course overriding the margin globally isn't an option, and gives catastrophic results.

**Comment by actionless** [comment]
in terms of border i was mostly concerned by gtk2 theme there theme engines are a bit limiting configuration possibilities for widgets

**Comment by actionless** [comment]
and regarding margin -- you can use it in the way like `margin=real_margin+border` but again making it all fit with gtk2 could be tricky

**Comment by cwendling** [comment]
> in terms of border i was mostly concerned by gtk2 theme there theme engines are a bit limiting configuration possibilities for the widgets

Damned, you're right.  Apparently with Murrine or Clearlooks there's no way to specify the border thickness, and the color is highly limited and not even applied everywhere (apparently notebooks don't care -- yes, even after switching them to the Murrine engine).

Is there any reasonable way around that?  Patching the engines? :S

**Comment by actionless** [comment]
the ideal solution will be implementing gtk3-theme-engine for gtk2 :3

**Comment by cwendling** [comment]
> the ideal solution will be implementing gtk3-theme-engine for gtk2 :3

hehe, sure… :)

On a more realistic scope, patching Murrine might be doable (I didn't check yet, but I expect it to be possible).  Would it be possible to use only Murrine, so not to have to patch 2 engines?

**Comment by actionless** [comment]
the only reason i've used `clearlooks` is to be able to use notebook tabs with a color stripe on an active one

so if we are going to patch murrine it can be implemented there



however depending on a patched murrine will make the application harder to redistribute -- it's one thing when we are talking about few bash and python scripts which are just working if all the dependencies installed and are not requiring additional build procedure. and it's completely different thing when we need to depend on some forked library which should go in a separate package


from the other point what do you think about improving the upstream murrine? i am wondering if they could accept the patches which are not changing any current behavior but adding new options/features

**Comment by cwendling** [comment]
> the only reason i've used `clearlooks` is to be able to use notebook tabs with a color stripe on an active one, so if we are going to patch murrine it can be implemented there

Indeed.

Though, it's also used to draw checkboxes, how do you feel about this one?

> from the other point what do you think about improving the upstream murrine? i am wondering if they could accept the patches which are not changing any current behavior but adding new options/features

Yeah I was thinking about patching upstream and try and make them accept the changes, not to fork it into a "oomox engine".  That might depend on how active the maintainer is and if he'd feel OK to add new feature to something that seem in a maintenance state for a while, but it'd worth trying it out.
Anyway, it's definitely the approach I'd be after.

**Comment by actionless** [comment]
i do not care too much about checkboxes' style in gtk2, the only requirement for them from me personally is what their color should suit in to the theme

**Comment by TiZ-EX1** [comment]
Murrine's code hasn't been touched in years. It's probably better to just treat GTK2 as legacy, that it won't be able to support features like this. Apps *should have* been moving to GTK3, but we know a lot are lagging behind if not due to lack of manpower (like XFCE), then due to uncooperative upstream ("we don't care that you needed this feature we removed; it wasn't important for our vision for your desktops and that's literally all we care about"). Basically, nobody's working on Murrine anymore. You'd have better luck generating images and kicking them over to the pixbuf engine.

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#4
