### ISSUE TITLE
Add buttons actions to the menu

### ISSUE THREAD

**Issue by alexarnaud** [actionless/oomox#79]
Dear oomox maintainer,

I’m a visual-impaired and I'm a colleague of cwendling. Thanks you for the great application you have made, it is really useful for low-vision people.

The keyboard-only users use F10 to access menu on software for simplicity and efficiency. On oomox at this time only the action “apply spotify theme” is available from the menu. I’m using mainly the keyboard due to the difficulty of mouse use and I have also difficulty to recognize icons.

Could it be possible to add all the buttons actions to the menu ?

Best regards.

**Comment by actionless** [comment]
Hi!
Thanks for the kind words and testing the application.
Do you suggest duplicating in the menu the same entries as buttons, right?
What do you think about adding Shortcuts window to oomox instead (by default you can open it by Ctrl+Shift+? in Nautilus and few other gtk+3, mostly gnome, apps)?
Since @cwendling already did some related changes it will be good to hear his opinion on the topic.

**Comment by alexarnaud** [comment]
Le 23/03/2017 à 15:55, Yauhen Kirylau a écrit :
> Hi!

Hi Yauhen,

> Do you suggest duplicating in the menu the same entries as buttons, right?

Yes, indeed.

> What do you think about adding Shortcuts window to oomox instead (by

The shortcuts would be discoverable by the menu. At this time we don't 
need to have more than a menu with the shortcuts in the right of each items.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by cwendling** [comment]
> Since @cwendling already did some related changes it will be good to hear his opinion on the topic.

I'm myself fine with duplicating the actions in the menu for discoverability.  To be honest, I don't really like the headerbar UI thing myself.
And I agree that currently keyboard navigation in it is not very good, let alone focusing it in the first place.  Toolbars-like things are in general not very nice to navigate through, at least nowhere as comfortable as menus.  Unfortunately other headerbar-heavy apps like GEdit or Evince have the same problem.

Some apps (like Firefox) have an hybrid interface for keyboard navigation, where a traditional menubar appears when pressing F10.  It's good for keyboard navigation and I guess nice if the preferred UI doesn't have a menu.
I'm however not sure how complex it'd be to do something like that.

Another option *could* be having F10 focus the headerbar so it could be navigated through, but while it might work, it's not the common behavior of F10 and might confuse some users.

**Comment by actionless** [comment]
Since oomox is very GTK+3-centric i think it's also important to take into consideration sticking to design choices of GNOME DE applications.

In GNOME design guidelines it is clearly stated:
> While the most frequently used actions for a view should be placed directly in the header bar, a header bar menu provides access to lesser-used actions. This ensures that the header bar isn’t overwhelmed with less interesting or useful controls.
(source: https://developer.gnome.org/hig/stable/header-bar-menus.html.en)

**Comment by actionless** [comment]
Also to address you problem I would recommend using plotinus, https://github.com/p-e-w/plotinus

![2017-03-25--1490470012_3840x2160_scrot](https://cloud.githubusercontent.com/assets/1655669/24325461/b1984e38-1199-11e7-831d-fa62dee0e217.png)
