### ISSUE TITLE
GTK3: Checkboxes hard to decipher

### ISSUE THREAD

**Issue by nixingizgood** [actionless/oomox#81]
First off, I love oomox. I am so happy that you've created this. Been wanting something like this forever. Seriously, its awesome. Thank you.

That being said, I do find it difficult to determine whether or not a checkbox is checked. Because the checkbox is a  greyed-out check instead of box, it can be difficult if the active color isn't very colorful or is similar to gray. 

A good example would be to right click (in the tray) on an instance Pulseaudio applet to change the audio output (pa-applet in arch/manjaro repo). On my system there is about 35 choices. With some of the themes it is very hard to see which selection is checked. Solarized-Light, for example. 

Can you please change the grayed-out checks into empty boxes, or give the option to do such? 

Thank you
oomox 1.2.1 from AUR

**Comment by actionless** [comment]
could you please provide screenshots (also sf it behave the same in the widget factory?) and oomox theme files?

**Comment by nixingizgood** [comment]
a screenshot showing difference, an oomox theme on the right

xfce theme on the left, and one of my oomox themes on the right
![for oomox](https://cloud.githubusercontent.com/assets/15900066/24634163/2dc1b506-1881-11e7-9ab3-ef92c08d78ec.png)

**Comment by nixingizgood** [comment]
theme file
[oomox-grayish.tar.gz](https://github.com/actionless/oomox/files/891599/oomox-grayish.tar.gz)

**Comment by actionless** [comment]
indeed, i think disabled one should be more transparent

**Comment by nixingizgood** [comment]
Cool, can't wait 👍 

Should also alter the bullets too, they are equally hard to decipher

**Comment by actionless** [comment]
actually, it's already quite transparent, i don't think it will be looking good if it will be more transparent:
https://github.com/actionless/oomox/blob/master/src/assets/menuitem-checkbox-unchecked.svg

so the solution i think should be using some other than in numix design for menu items. contributions are welcome

**Comment by actionless** [comment]
please add also the radios

**Comment by nixingizgood** [comment]
[Adwaita_radios.tar.gz](https://github.com/actionless/oomox/files/906829/Adwaita_radios.tar.gz)

**Comment by actionless** [comment]
thanks, i will do some modifications and hopefully release during the
weekend
