### ISSUE TITLE
gtk2 pre-scale

### ISSUE THREAD

**Issue by kindlychung** [actionless/oomox#82]
According to Arch linux wiki:

> Scaling of UI elements is not supported by the toolkit itself, however it's possible to generate a theme with elements pre-scaled for HiDPI display using oomox-gitAUR.

How does one pre-scale elements in oomox?

The HiDPI option doesn't have much of an effect: http://i.imgur.com/Hd2hNDT.png

**Comment by actionless** [comment]
you can find out widget class of that panel in inkscape and add a rule for it to this file:
https://github.com/actionless/oomox/blob/master/src/gtk-2.0/gtkrc.hidpi

this tool should be helpful:
https://chipx86.github.io/gtkparasite/

**Comment by actionless** [comment]
also icon sizes could be overriden by you settings manager, here is an example of how it's done in `xsettingsd`:

```
Gtk/IconSizes "panel-menu=40,40:panel=40,40:gtk-menu=24,24:gtk-large-toolbar=40,40:gtk-small-toolbar=40,40:gtk-button=24,24"
```

**Comment by actionless** [comment]
if there are any volunteers to implement that pre-scaling here is an example:
https://github.com/nana-4/Flat-Plat/pull/142

but in this case it will also take some effort to re-implement border radius option for buttons/inputs

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#5
