### ISSUE TITLE
No drop shadows

### ISSUE THREAD

**Issue by ddnexus** [actionless/oomox#84]
There are no drop shadows for any of the generated themes. Any way to add them?
Using Ubuntu-GNOME 17.04, with or without Wayland.

**Comment by actionless** [comment]
which GTK+3 version is shipped in 17.04?

**Comment by actionless** [comment]
how and with which other GTK theme i can reproduce that behavior?

**Comment by ddnexus** [comment]
I managed to make it work by locally adding the decoration section here:
https://github.com/GNOME/gtk/blob/master/gtk/theme/Adwaita/gtk-contained.css#L4519

Gnome version 3.24.0

**Comment by actionless** [comment]
oh, i have that block overriden in my local gtk.css because that feature not works with tiling wm's smoothly: https://github.com/actionless/oomox#using-with-tiling-wms

so for me is harder to notice if something is breaks in that area, i'll take a look deeper what part of decoration is missing now

**Comment by ddnexus** [comment]
if for 'tiling" you mean apps that split the window (like "tilix" for examplle) I don't notice any problem with it in my setup. What would be the problem? How could I check that?

**Comment by actionless** [comment]
no, it's about tiling window managers, like `i3` or `awesome wm`

**Comment by EightLegs** [comment]
I'm also cannot generate themes with window drop shadows.

Also, changing the "focused window border" color seems to have no effect on the generated theme.

Thanks for the hard work on what looks like a great package!

**Comment by actionless** [comment]
could you try reverting this change locally?
https://github.com/actionless/oomox/commit/f99890a8c3fc4c579cfae01f1cb3fbab6c8f7458

it was added because that thing was working correctly only in GNOME, so in other DE's/WM's all the windows had an active border color

**Comment by EightLegs** [comment]
Thanks. I tried changing gtk-3.20/scss/widgets/_window.scss to the text below, but it made no difference to either the drop shadow (no shadow) or border color (no change from black).

@include exports("window") {
    decoration {
        $_wm_border: if($variant == 'light', transparentize($black, .77), transparentize($borders_color, .1));

        border-radius: $roundness $roundness 0 0;
        // lamefun trick to get rounded borders regardless of CSD use
        //border-width: 0;

        box-shadow: 0 3px 9px 1px transparentize($black, .3), 0 0 0 1px $wm_border_focused; //doing borders with box-shadow
        /* this is used for the resize cursor area */
        //margin: $spacing * 3;

        border-width: $spacing % 2;
        border-style: solid;
        border-color: $wm_border_focused;
        //@TODO:
        //border-color: $wm_border_unfocused;


        &:backdrop {
            box-shadow: 0 3px 9px 1px transparent, 0 2px 6px 2px transparentize($black, .6), 0 0 0 1px $wm_border_unfocused;
            border-color: $wm_border_unfocused;
            transition: 200ms ease-out;
        }

**Comment by actionless** [comment]
sorry for stupid question, but have you re-exported the theme after changing base scss?

**Comment by EightLegs** [comment]
Thanks. I'm new to creating themes, so perhaps I had been in error earlier. I had been editing the _window.scss file in the outputted theme files, not the original oomox file.

The edit you had suggested was already present in /opt/oomox/src/gtk-3.20/scss/widgets/_window.scss.

I edited this file as follows, and successfully got the window border color to change. Still no drop shadow.

File now includes, starting at line 17:

        border-width: $spacing % 2;
        border-style: solid;
        border-color: $wm_border_focused;
        //@TODO:
        //border-color: $wm_border_unfocused;

**Comment by EightLegs** [comment]
Note that uncommenting line 13 in /opt/oomox/src/gtk-3.20/scss/widgets/_window.scss lets oomox  create drop shadows... but it creates them for all windows, not just the active one.

**Comment by actionless** [comment]
and uncommenting line 25?

**Comment by EightLegs** [comment]
Uncommenting both line 13 and 25 creates drop shadows on every window, not just the active one.

**Comment by actionless** [comment]
what about only 25?

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#6
