### ISSUE TITLE
Gnome Shell Theme

### ISSUE THREAD

**Issue by ddnexus** [actionless/oomox#86]
Currently the Gnome Shell is not affected by the theme, and no Shell theme is produced.
A really useful addition would be generating the assets and css for the Gnome Shell, consistent with the Oomox theme.
How difficult would that be?

**Comment by actionless** [comment]
if you are interested you can take default Numix theme for Gnome Shell and replace all the hardcoded colors with template variables (like `#%BG%`):
https://github.com/actionless/oomox/blob/master/src/gtk-3.20/scss/_global.scss#L6-L17

**Comment by ddnexus** [comment]
I am not sure I understand what you mean. AFAIK there is no Numix Gnome Shell theme currently working (or at least changing the complete Gnome Shell consistently with the GTK3 theme).

**Comment by actionless** [comment]
try to use gnome-shell theme from here:
https://www.gnome-look.org/p/1137261/

**Comment by ddnexus** [comment]
Thanks. However that offers only a partial coverage of the Gnome Shell theme.

**Comment by actionless** [comment]
i'll leave this open in case if here will be any other volunteer to get gnome-shell theme

**Comment by actionless** [comment]
This issue was moved to actionless/oomox-gtk-theme#7
