### ISSUE TITLE
Version 1.2.6.1 fails to export any theme

### ISSUE THREAD

**Issue by HerborenInVlammen** [actionless/oomox#89]
Version 1.2.6.1 fails to export any theme and gives the following output/error message (note that regardless of template chosen, the error message is the same aside from the theme name):

rm -rf "gtk-3.0/dist"
rm -f "gtk-3.0/gtk.gresource"
rm -rf "gtk-3.20/dist"
rm -f "gtk-3.20/gtk.gresource"
rm -rf "/home/prodigal/.themes/oomox-QuakeWorld/dist"
mkdir -p gtk-3.20/dist
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
Error: Invalid CSS after "...tlebar_bg_color": expected expression (e.g. 1px, bold), was "@dark_bg_color;"
        on line 36 of gtk-3.20/scss/_colors.scss
>> @define-color titlebar_bg_color @dark_bg_color;
   -------------------------------^
sassc: symbol lookup error: sassc: undefined symbol: sass_delete_options
Makefile:27: recipe for target 'css_gtk320' failed
make: *** [css_gtk320] Error 127

Prior version before update worked great.

**Comment by actionless** [comment]
please attach output of `sassc -v`

**Comment by EightLegs** [comment]
I'm having the same problem.

rm -rf "gtk-3.0/dist"
rm -f "gtk-3.0/gtk.gresource"
rm -rf "gtk-3.20/dist"
rm -f "gtk-3.20/gtk.gresource"
rm -rf "/home/richard/.themes/oomox-numix/dist"
mkdir -p gtk-3.20/dist
sassc -I "gtk-3.20/scss" "gtk-3.20/scss/gtk.scss" "gtk-3.20/dist/gtk.css"
Error: Invalid CSS after "...tlebar_bg_color": expected expression (e.g. 1px, bold), was "@dark_bg_color;"
        on line 36 of gtk-3.20/scss/_colors.scss
>> @define-color titlebar_bg_color @dark_bg_color;
   -------------------------------^
Makefile:27: recipe for target 'css_gtk320' failed
make: *** [css_gtk320] Error 1

Oomox 1.2.6-1~webupd8~2
Ubuntu 16.04.2
Gnome desktop 3.20

Here's the output of sassc -v:

sassc: 3.3.2
libsass: 3.3.4
sass2scss: 1.0.5

Thanks very much. This is my first time using Oomox. It looks like a great app.

**Comment by actionless** [comment]
could you try with versions 3.4 of sassc and libsass?

**Comment by EightLegs** [comment]
Sassc 3.4 solved the problem. Thanks.

For those on Ubuntu 16.04, here are the steps I used to install sassc 3.4: https://askubuntu.com/questions/849057/how-to-install-libsass-on-ubuntu-16-04

**Comment by actionless** [comment]
thanks for testing!
i will update the readme to mention that

**Comment by actionless** [comment]
btw compatibility with `ruby-sass` wasn't broken, in order to fallback to use it, just copy `Makefile` from the previous release (it's makefile of gtk3 theme, not oomox app)
