### ISSUE TITLE
customizing colours results in "sed: no input files"

### ISSUE THREAD

**Issue by NattyNarwhal** [actionless/oomox#9]
can be tested on Ubuntu 14.04

**Comment by NattyNarwhal** [comment]
interestingly, it changed the theme. I had tried on OpenBSD (after hacking the script to use the GNU versions of coreutils, as it uses GNU extensions) and it didn't even bother changing them

**Comment by actionless** [comment]
so it's not working in ubuntu or in OpenBSD?
if latter then i think it can be about grep options, i can write a case for it then.

**Comment by actionless** [comment]
fixed by https://github.com/actionless/oomox/commit/b333e0de8ed7758414d78fb4b12d1d901f149475
