### ISSUE TITLE
Latest version generated myriads of GTK error messages...

### ISSUE THREAD

**Issue by HerborenInVlammen** [actionless/oomox#90]
Latest Oomox version generates myriads of GTK error messages when apps are launched via terminal.  See below:  (Note that I tried attaching a file that contained the following info but all file types were rejected.  Note also that the apps listed below are selected at random and are not meant to be a comprehensive list of GTK apps that give the errors; they were selected at random).

prodigal@GVS:~$ synaptic:
(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(synaptic:13571): Gtk-WARNING **: Theme parsing error: gtk.css:6244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Exfalso:
prodigal@GVS:~$ exfalso

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(exfalso:13655): Gtk-WARNING **: Theme parsing error: gtk.css:6244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

prodigal@GVS:~$ audacity:
(Audacity:13727): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()

Thunderbird:
prodigal@GVS:~$ thunderbird

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924):
 Gtk-WARNING **: Theme parsing error: gtk.css:6211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(thunderbird:13924): Gtk-WARNING **: Theme parsing error: gtk.css:6244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

Firefox:
prodigal@GVS:~$ firefox

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:14135): Gtk-WARNING **: Theme parsing error: gtk.css:6244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

Handbrake:
prodigal@GVS:~$ ghb

(ghb:14525): Gtk-WARNING **: Theme parsing error: <data>:43:23: The :prelight pseudo-class is deprecated. Use :hover instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6187:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6191:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6191:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6195:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6205:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6205:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6205:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6205:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6211:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6211:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6220:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6224:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6224:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6228:35: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6238:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6238:75: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6238:114: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6238:152: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6244:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(ghb:14525): Gtk-WARNING **: Theme parsing error: gtk.css:6244:91: The :insensitive pseudo-class is deprecated. Use :disabled instead.

And so on ... this did not occur with previous versions of Oomox

**Comment by actionless** [comment]
which version do you use?

that was fixed already in https://github.com/actionless/oomox/releases/tag/1.2.5

**Comment by actionless** [comment]
reporter is gone
