### ISSUE TITLE
Makefile produces an error when no arguments is sent

### ISSUE THREAD

**Issue by alexarnaud** [actionless/oomox#92]
Dear all,

I'm in process to package Oomox for Debian 9 "Stretch" and I notice that when debhelper command executes "make" I obtain the following error :

```
sassc -I "gtk-3.0/scss" "gtk-3.0/scss/gtk.scss" "gtk-3.0/dist/gtk.css"
Internal Error: File to read not found or unreadable: gtk-3.0/scss/gtk.scss
Makefile:19: recipe for target 'css_gtk3' failed
make: *** [css_gtk3] Error 1
```

Best regards.

**Comment by actionless** [comment]
the reference package example is here:
https://github.com/actionless/oomox/blob/master/PKGBUILD

**Comment by actionless** [comment]
no there is no any confusing Makefile there anymore
