### ISSUE TITLE
Extend oomox compatibility to other custom themes?

### ISSUE THREAD

**Issue by Warmuser** [actionless/oomox#94]
There are many interesting themes to customize, could be possibile to extend the oomox compatibility with  other custom themes like:

- Adapta https://github.com/adapta-project/adapta-gtk-theme
- Flat-pat https://github.com/nana-4/Flat-Plat
- Paper https://github.com/snwh/paper-gtk-theme
- Flat Remix https://github.com/daniruiz/Flat-Remix-GNOME-theme
- Arc Theme https://github.com/horst3180/arc-theme
- Vimix https://github.com/vinceliuice/vimix-gtk-themes

Let me know if it possible, thanks! :)

**Comment by actionless** [comment]
yes, it's possible
i will be happy to merge to oomox pull requests with any new themes

**Comment by Warmuser** [comment]
Ok thanks, anyway I want to add also Vimix to the request, because its a really valid theme.

**Comment by actionless** [comment]
btw i forgot to mention what it won't be possible for any themes which are using any bitmap image assets (they first should be replaced to SVG)

**Comment by Warmuser** [comment]
Ok, I opened some compatibility requests for oomox. :)

**Comment by actionless** [comment]
thanks! please mention me with an `@` if it will be needed any my input in those conversations

**Comment by Warmuser** [comment]
Ok :)

**Comment by actionless** [comment]
Flat-Plat is ready, all other quite similar to it, except for `arc-theme`, i personally like `arc` and `vertex` themes

**Comment by Warmuser** [comment]
Fantastic! :)

**Comment by actionless** [comment]
submodule names need to be updated in PKGBUILD, now it should work fine

**Comment by untoreh** [comment]
the materia theme style does not allow menu/toolbar text is that a limitation of the theme itself? Because the menu/toolbar text inherits the background color and not even foreground/text color

**Comment by actionless** [comment]
sorta, in original theme those colors are the same as well, i can later on add an option to switch between using such pattern as currently (as in normal Materia theme) and using the same colors as normal background (as in Materia-Light theme)

**Comment by actionless** [comment]
since there was no feedback from other themes' devs i think this can be closed by now

**Comment by untoreh** [comment]
I think right click menus have the same problem

**Comment by actionless** [comment]
@untoreh i've reported that issue already: https://github.com/nana-4/materia-theme/issues/183#issuecomment-348741654

**Comment by actionless** [comment]
@untoreh fixed in c69a336

**Comment by untoreh** [comment]
menu is fixed, however menubar background now has selection highlight color

**Comment by actionless** [comment]
@untoreh please try with 3849cc48021b45fcaabfbe12a0fc312f22e65c1b
