### ISSUE TITLE
custom colors

### ISSUE THREAD

**Issue by Joseph65** [actionless/oomox#95]
i want the theme to have the same color except the text and highlight like this 
![screenshot_2017-08-21_00-15-34](https://user-images.githubusercontent.com/12629965/29590978-2d83c020-8762-11e7-8d58-f76c41ea23f9.png)
here is the theme i am editing
[oomox-noble-dark.zip](https://github.com/actionless/oomox/files/1243618/oomox-noble-dark.zip)
and the screenshot of it
![screenshot_2017-08-22_17-42-14](https://user-images.githubusercontent.com/12629965/29591169-e4f8b4ae-8762-11e7-965d-2f5a05109cfd.png)
i am on xubuntu

**Comment by actionless** [comment]
button style is described here:
https://github.com/actionless/oomox-gtk-theme/blob/15eb243288a1066f4facc07e9ada55abac770508/src/gtk-3.20/scss/widgets/_button.scss

but also `gtk-inspector` (Ctrl+Shift+D) is quite helpful
