### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by HanaO00** [actionless/oomox#96]
Hello, do i need to install the numix gtk themes for use with oomox ?

The theme created is installed in ~/.themes ?

In some themes, in the gtk.css i have resource..., where is the real gtk ?

Thanks

**Comment by actionless** [comment]
installation instructions are provided in readme:
https://github.com/actionless/oomox/blob/master/README.md

if it is look too technical to read you can also follow one of the links in the bottom, where more user-oriented articles and video are provided
